// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AbilityDefHandle : RemoteTableHandle<EventContext, AbilityDef>
        {
            protected override string RemoteTableName => "ability_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AbilityDef row) => row.Id;

                public IdUniqueIndex(AbilityDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal AbilityDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(AbilityDef row) => row.Id;
        }

        public readonly AbilityDefHandle AbilityDef;
    }

    public sealed class AbilityDefCols
    {
        public global::SpacetimeDB.Col<AbilityDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<AbilityDef, string> Name { get; }
        public global::SpacetimeDB.Col<AbilityDef, string> Description { get; }
        public global::SpacetimeDB.Col<AbilityDef, AbilityType> Type { get; }
        public global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<TargetType>> ValidTargets { get; }
        public global::SpacetimeDB.Col<AbilityDef, int> BasePower { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> BaseRange { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> BaseRadius { get; }
        public global::SpacetimeDB.Col<AbilityDef, ulong> CooldownMs { get; }
        public global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<ResourceCost>> ResourceCosts { get; }
        public global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<AbilityMod>> GrantedMods { get; }
        public global::SpacetimeDB.Col<AbilityDef, ulong> EffectDurationMs { get; }
        public global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<ulong>> AffectedAbilityIds { get; }
        public global::SpacetimeDB.Col<AbilityDef, TerrainType> SpawnedTerrainType { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> TerrainSizeX { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> TerrainSizeY { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> TerrainSizeZ { get; }
        public global::SpacetimeDB.Col<AbilityDef, int> TerrainMaxHealth { get; }
        public global::SpacetimeDB.Col<AbilityDef, DamageDistribution> Distribution { get; }
        public global::SpacetimeDB.Col<AbilityDef, bool> AllowSubSquadTargeting { get; }
        public global::SpacetimeDB.Col<AbilityDef, TargetingMode> Targeting { get; }
        public global::SpacetimeDB.Col<AbilityDef, float> ProjectileSpeed { get; }

        public AbilityDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<AbilityDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<AbilityDef, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<AbilityDef, string>(tableName, "description");
            Type = new global::SpacetimeDB.Col<AbilityDef, AbilityType>(tableName, "type");
            ValidTargets = new global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<TargetType>>(tableName, "valid_targets");
            BasePower = new global::SpacetimeDB.Col<AbilityDef, int>(tableName, "base_power");
            BaseRange = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "base_range");
            BaseRadius = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "base_radius");
            CooldownMs = new global::SpacetimeDB.Col<AbilityDef, ulong>(tableName, "cooldown_ms");
            ResourceCosts = new global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<ResourceCost>>(tableName, "resource_costs");
            GrantedMods = new global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<AbilityMod>>(tableName, "granted_mods");
            EffectDurationMs = new global::SpacetimeDB.Col<AbilityDef, ulong>(tableName, "effect_duration_ms");
            AffectedAbilityIds = new global::SpacetimeDB.Col<AbilityDef, System.Collections.Generic.List<ulong>>(tableName, "affected_ability_ids");
            SpawnedTerrainType = new global::SpacetimeDB.Col<AbilityDef, TerrainType>(tableName, "spawned_terrain_type");
            TerrainSizeX = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "terrain_size_x");
            TerrainSizeY = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "terrain_size_y");
            TerrainSizeZ = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "terrain_size_z");
            TerrainMaxHealth = new global::SpacetimeDB.Col<AbilityDef, int>(tableName, "terrain_max_health");
            Distribution = new global::SpacetimeDB.Col<AbilityDef, DamageDistribution>(tableName, "distribution");
            AllowSubSquadTargeting = new global::SpacetimeDB.Col<AbilityDef, bool>(tableName, "allow_sub_squad_targeting");
            Targeting = new global::SpacetimeDB.Col<AbilityDef, TargetingMode>(tableName, "targeting");
            ProjectileSpeed = new global::SpacetimeDB.Col<AbilityDef, float>(tableName, "projectile_speed");
        }
    }

    public sealed class AbilityDefIxCols
    {
        public global::SpacetimeDB.IxCol<AbilityDef, ulong> Id { get; }

        public AbilityDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<AbilityDef, ulong>(tableName, "id");
        }
    }
}
