// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AbilityCooldownHandle : RemoteTableHandle<EventContext, AbilityCooldown>
        {
            protected override string RemoteTableName => "ability_cooldown";

            public sealed class ByGpAbilityIndex : BTreeIndexBase<(ulong GamePlayerId, ulong AbilityId)>
            {
                protected override (ulong GamePlayerId, ulong AbilityId) GetKey(AbilityCooldown row) => (row.GamePlayerId, row.AbilityId);

                public ByGpAbilityIndex(AbilityCooldownHandle table) : base(table) { }
            }

            public readonly ByGpAbilityIndex ByGpAbility;

            public sealed class GamePlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(AbilityCooldown row) => row.GamePlayerId;

                public GamePlayerIdIndex(AbilityCooldownHandle table) : base(table) { }
            }

            public readonly GamePlayerIdIndex GamePlayerId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AbilityCooldown row) => row.Id;

                public IdUniqueIndex(AbilityCooldownHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal AbilityCooldownHandle(DbConnection conn) : base(conn)
            {
                ByGpAbility = new(this);
                GamePlayerId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(AbilityCooldown row) => row.Id;
        }

        public readonly AbilityCooldownHandle AbilityCooldown;
    }

    public sealed class AbilityCooldownCols
    {
        public global::SpacetimeDB.Col<AbilityCooldown, ulong> Id { get; }
        public global::SpacetimeDB.Col<AbilityCooldown, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.Col<AbilityCooldown, ulong> AbilityId { get; }
        public global::SpacetimeDB.Col<AbilityCooldown, SpacetimeDB.Timestamp> ReadyAt { get; }

        public AbilityCooldownCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<AbilityCooldown, ulong>(tableName, "id");
            GamePlayerId = new global::SpacetimeDB.Col<AbilityCooldown, ulong>(tableName, "game_player_id");
            AbilityId = new global::SpacetimeDB.Col<AbilityCooldown, ulong>(tableName, "ability_id");
            ReadyAt = new global::SpacetimeDB.Col<AbilityCooldown, SpacetimeDB.Timestamp>(tableName, "ready_at");
        }
    }

    public sealed class AbilityCooldownIxCols
    {
        public global::SpacetimeDB.IxCol<AbilityCooldown, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<AbilityCooldown, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.IxCol<AbilityCooldown, ulong> AbilityId { get; }

        public AbilityCooldownIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<AbilityCooldown, ulong>(tableName, "id");
            GamePlayerId = new global::SpacetimeDB.IxCol<AbilityCooldown, ulong>(tableName, "game_player_id");
            AbilityId = new global::SpacetimeDB.IxCol<AbilityCooldown, ulong>(tableName, "ability_id");
        }
    }
}
