// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BattleLogHandle : RemoteTableHandle<EventContext, BattleLogEntry>
        {
            protected override string RemoteTableName => "battle_log";

            public sealed class ActorEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(BattleLogEntry row) => row.ActorEntityId;

                public ActorEntityIdIndex(BattleLogHandle table) : base(table) { }
            }

            public readonly ActorEntityIdIndex ActorEntityId;

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(BattleLogEntry row) => row.GameSessionId;

                public GameSessionIdIndex(BattleLogHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BattleLogEntry row) => row.Id;

                public IdUniqueIndex(BattleLogHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BattleLogHandle(DbConnection conn) : base(conn)
            {
                ActorEntityId = new(this);
                GameSessionId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(BattleLogEntry row) => row.Id;
        }

        public readonly BattleLogHandle BattleLog;
    }

    public sealed class BattleLogCols
    {
        public global::SpacetimeDB.Col<BattleLogEntry, ulong> Id { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, SpacetimeDB.Timestamp> OccurredAt { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, BattleLogEventType> EventType { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, ulong> ActorEntityId { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, ulong> AbilityId { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, System.Collections.Generic.List<ulong>> TargetEntityIds { get; }
        public global::SpacetimeDB.Col<BattleLogEntry, int> ResolvedPower { get; }

        public BattleLogCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BattleLogEntry, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<BattleLogEntry, ulong>(tableName, "game_session_id");
            OccurredAt = new global::SpacetimeDB.Col<BattleLogEntry, SpacetimeDB.Timestamp>(tableName, "occurred_at");
            EventType = new global::SpacetimeDB.Col<BattleLogEntry, BattleLogEventType>(tableName, "event_type");
            ActorEntityId = new global::SpacetimeDB.Col<BattleLogEntry, ulong>(tableName, "actor_entity_id");
            AbilityId = new global::SpacetimeDB.Col<BattleLogEntry, ulong>(tableName, "ability_id");
            TargetEntityIds = new global::SpacetimeDB.Col<BattleLogEntry, System.Collections.Generic.List<ulong>>(tableName, "target_entity_ids");
            ResolvedPower = new global::SpacetimeDB.Col<BattleLogEntry, int>(tableName, "resolved_power");
        }
    }

    public sealed class BattleLogIxCols
    {
        public global::SpacetimeDB.IxCol<BattleLogEntry, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<BattleLogEntry, ulong> GameSessionId { get; }
        public global::SpacetimeDB.IxCol<BattleLogEntry, ulong> ActorEntityId { get; }

        public BattleLogIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BattleLogEntry, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<BattleLogEntry, ulong>(tableName, "game_session_id");
            ActorEntityId = new global::SpacetimeDB.IxCol<BattleLogEntry, ulong>(tableName, "actor_entity_id");
        }
    }
}
