// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CapturePointHandle : RemoteTableHandle<EventContext, CapturePoint>
        {
            protected override string RemoteTableName => "capture_point";

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CapturePoint row) => row.GameSessionId;

                public GameSessionIdIndex(CapturePointHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CapturePoint row) => row.Id;

                public IdUniqueIndex(CapturePointHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CapturePointHandle(DbConnection conn) : base(conn)
            {
                GameSessionId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(CapturePoint row) => row.Id;
        }

        public readonly CapturePointHandle CapturePoint;
    }

    public sealed class CapturePointCols
    {
        public global::SpacetimeDB.Col<CapturePoint, ulong> Id { get; }
        public global::SpacetimeDB.Col<CapturePoint, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<CapturePoint, float> PosX { get; }
        public global::SpacetimeDB.Col<CapturePoint, float> PosZ { get; }
        public global::SpacetimeDB.Col<CapturePoint, float> Radius { get; }
        public global::SpacetimeDB.Col<CapturePoint, byte> OwningTeam { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> InfluenceTeam1 { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> InfluenceTeam2 { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> MaxInfluence { get; }

        public CapturePointCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CapturePoint, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<CapturePoint, ulong>(tableName, "game_session_id");
            PosX = new global::SpacetimeDB.Col<CapturePoint, float>(tableName, "pos_x");
            PosZ = new global::SpacetimeDB.Col<CapturePoint, float>(tableName, "pos_z");
            Radius = new global::SpacetimeDB.Col<CapturePoint, float>(tableName, "radius");
            OwningTeam = new global::SpacetimeDB.Col<CapturePoint, byte>(tableName, "owning_team");
            InfluenceTeam1 = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "influence_team_1");
            InfluenceTeam2 = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "influence_team_2");
            MaxInfluence = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "max_influence");
        }
    }

    public sealed class CapturePointIxCols
    {
        public global::SpacetimeDB.IxCol<CapturePoint, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<CapturePoint, ulong> GameSessionId { get; }

        public CapturePointIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CapturePoint, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<CapturePoint, ulong>(tableName, "game_session_id");
        }
    }
}
