// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatSessionHandle : RemoteTableHandle<EventContext, ChatSession>
        {
            protected override string RemoteTableName => "chat_session";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatSession row) => row.Id;

                public IdUniqueIndex(ChatSessionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(ChatSession row) => row.Name;

                public NameIndex(ChatSessionHandle table) : base(table) { }
            }

            public readonly NameIndex Name;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ChatSession row) => row.Owner;

                public OwnerIndex(ChatSessionHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal ChatSessionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(ChatSession row) => row.Id;
        }

        public readonly ChatSessionHandle ChatSession;
    }

    public sealed class ChatSessionCols
    {
        public global::SpacetimeDB.Col<ChatSession, ulong> Id { get; }
        public global::SpacetimeDB.Col<ChatSession, SpacetimeDB.Timestamp> TimeCreated { get; }
        public global::SpacetimeDB.Col<ChatSession, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<ChatSession, string> Name { get; }
        public global::SpacetimeDB.Col<ChatSession, bool> Active { get; }

        public ChatSessionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ChatSession, ulong>(tableName, "id");
            TimeCreated = new global::SpacetimeDB.Col<ChatSession, SpacetimeDB.Timestamp>(tableName, "time_created");
            Owner = new global::SpacetimeDB.Col<ChatSession, SpacetimeDB.Identity>(tableName, "owner");
            Name = new global::SpacetimeDB.Col<ChatSession, string>(tableName, "name");
            Active = new global::SpacetimeDB.Col<ChatSession, bool>(tableName, "active");
        }
    }

    public sealed class ChatSessionIxCols
    {
        public global::SpacetimeDB.IxCol<ChatSession, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ChatSession, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<ChatSession, string> Name { get; }

        public ChatSessionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ChatSession, ulong>(tableName, "id");
            Owner = new global::SpacetimeDB.IxCol<ChatSession, SpacetimeDB.Identity>(tableName, "owner");
            Name = new global::SpacetimeDB.IxCol<ChatSession, string>(tableName, "name");
        }
    }
}
