// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatSessionPlayerHandle : RemoteTableHandle<EventContext, ChatSessionPlayer>
        {
            protected override string RemoteTableName => "chat_session_player";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatSessionPlayer row) => row.Id;

                public IdUniqueIndex(ChatSessionPlayerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ChatSessionPlayer row) => row.PlayerIdentity;

                public PlayerIdentityIndex(ChatSessionPlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdentityIndex PlayerIdentity;

            public sealed class SessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ChatSessionPlayer row) => row.SessionId;

                public SessionIdIndex(ChatSessionPlayerHandle table) : base(table) { }
            }

            public readonly SessionIdIndex SessionId;

            internal ChatSessionPlayerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerIdentity = new(this);
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(ChatSessionPlayer row) => row.Id;
        }

        public readonly ChatSessionPlayerHandle ChatSessionPlayer;
    }

    public sealed class ChatSessionPlayerCols
    {
        public global::SpacetimeDB.Col<ChatSessionPlayer, ulong> Id { get; }
        public global::SpacetimeDB.Col<ChatSessionPlayer, SpacetimeDB.Identity> PlayerIdentity { get; }
        public global::SpacetimeDB.Col<ChatSessionPlayer, ulong> SessionId { get; }

        public ChatSessionPlayerCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ChatSessionPlayer, ulong>(tableName, "id");
            PlayerIdentity = new global::SpacetimeDB.Col<ChatSessionPlayer, SpacetimeDB.Identity>(tableName, "player_identity");
            SessionId = new global::SpacetimeDB.Col<ChatSessionPlayer, ulong>(tableName, "session_id");
        }
    }

    public sealed class ChatSessionPlayerIxCols
    {
        public global::SpacetimeDB.IxCol<ChatSessionPlayer, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ChatSessionPlayer, SpacetimeDB.Identity> PlayerIdentity { get; }
        public global::SpacetimeDB.IxCol<ChatSessionPlayer, ulong> SessionId { get; }

        public ChatSessionPlayerIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ChatSessionPlayer, ulong>(tableName, "id");
            PlayerIdentity = new global::SpacetimeDB.IxCol<ChatSessionPlayer, SpacetimeDB.Identity>(tableName, "player_identity");
            SessionId = new global::SpacetimeDB.IxCol<ChatSessionPlayer, ulong>(tableName, "session_id");
        }
    }
}
