// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CorpseHandle : RemoteTableHandle<EventContext, Corpse>
        {
            protected override string RemoteTableName => "corpse";

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Corpse row) => row.GameSessionId;

                public GameSessionIdIndex(CorpseHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Corpse row) => row.Id;

                public IdUniqueIndex(CorpseHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CorpseHandle(DbConnection conn) : base(conn)
            {
                GameSessionId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(Corpse row) => row.Id;
        }

        public readonly CorpseHandle Corpse;
    }

    public sealed class CorpseCols
    {
        public global::SpacetimeDB.Col<Corpse, ulong> Id { get; }
        public global::SpacetimeDB.Col<Corpse, ulong> GameSessionId { get; }
        public global::SpacetimeDB.NullableCol<Corpse, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.Col<Corpse, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<Corpse, DbVector3> Position { get; }
        public global::SpacetimeDB.Col<Corpse, float> RotationY { get; }

        public CorpseCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "game_session_id");
            GamePlayerId = new global::SpacetimeDB.NullableCol<Corpse, ulong>(tableName, "game_player_id");
            PlayerId = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "player_id");
            Position = new global::SpacetimeDB.Col<Corpse, DbVector3>(tableName, "position");
            RotationY = new global::SpacetimeDB.Col<Corpse, float>(tableName, "rotation_y");
        }
    }

    public sealed class CorpseIxCols
    {
        public global::SpacetimeDB.IxCol<Corpse, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Corpse, ulong> GameSessionId { get; }

        public CorpseIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Corpse, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<Corpse, ulong>(tableName, "game_session_id");
        }
    }
}
