// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GamePlayerHandle : RemoteTableHandle<EventContext, GamePlayer>
        {
            protected override string RemoteTableName => "game_player";

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GamePlayer row) => row.GameSessionId;

                public GameSessionIdIndex(GamePlayerHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GamePlayer row) => row.Id;

                public IdUniqueIndex(GamePlayerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GamePlayer row) => row.PlayerId;

                public PlayerIdIndex(GamePlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal GamePlayerHandle(DbConnection conn) : base(conn)
            {
                GameSessionId = new(this);
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(GamePlayer row) => row.Id;
        }

        public readonly GamePlayerHandle GamePlayer;
    }

    public sealed class GamePlayerCols
    {
        public global::SpacetimeDB.Col<GamePlayer, ulong> Id { get; }
        public global::SpacetimeDB.Col<GamePlayer, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<GamePlayer, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<GamePlayer, byte> TeamSlot { get; }
        public global::SpacetimeDB.Col<GamePlayer, bool> Active { get; }
        public global::SpacetimeDB.Col<GamePlayer, DbVector3> Position { get; }

        public GamePlayerCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "game_session_id");
            PlayerId = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "player_id");
            TeamSlot = new global::SpacetimeDB.Col<GamePlayer, byte>(tableName, "team_slot");
            Active = new global::SpacetimeDB.Col<GamePlayer, bool>(tableName, "active");
            Position = new global::SpacetimeDB.Col<GamePlayer, DbVector3>(tableName, "position");
        }
    }

    public sealed class GamePlayerIxCols
    {
        public global::SpacetimeDB.IxCol<GamePlayer, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GamePlayer, ulong> GameSessionId { get; }
        public global::SpacetimeDB.IxCol<GamePlayer, ulong> PlayerId { get; }

        public GamePlayerIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GamePlayer, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<GamePlayer, ulong>(tableName, "game_session_id");
            PlayerId = new global::SpacetimeDB.IxCol<GamePlayer, ulong>(tableName, "player_id");
        }
    }
}
