// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GamePlayerHandle : RemoteTableHandle<EventContext, GamePlayer>
        {
            protected override string RemoteTableName => "game_player";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GamePlayer row) => row.EntityId;

                public EntityIdUniqueIndex(GamePlayerHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(GamePlayer row) => row.PlayerId;

                public PlayerIdIndex(GamePlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal GamePlayerHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(GamePlayer row) => row.EntityId;
        }

        public readonly GamePlayerHandle GamePlayer;
    }

    public sealed class GamePlayerCols
    {
        public global::SpacetimeDB.Col<GamePlayer, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<GamePlayer, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<GamePlayer, bool> Active { get; }
        public global::SpacetimeDB.Col<GamePlayer, ulong> TargetEntityId { get; }

        public GamePlayerCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "entity_id");
            PlayerId = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "player_id");
            Active = new global::SpacetimeDB.Col<GamePlayer, bool>(tableName, "active");
            TargetEntityId = new global::SpacetimeDB.Col<GamePlayer, ulong>(tableName, "target_entity_id");
        }
    }

    public sealed class GamePlayerIxCols
    {
        public global::SpacetimeDB.IxCol<GamePlayer, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<GamePlayer, ulong> PlayerId { get; }

        public GamePlayerIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<GamePlayer, ulong>(tableName, "entity_id");
            PlayerId = new global::SpacetimeDB.IxCol<GamePlayer, ulong>(tableName, "player_id");
        }
    }
}
