// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LoadoutHandle : RemoteTableHandle<EventContext, Loadout>
        {
            protected override string RemoteTableName => "loadout";

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Loadout row) => row.GameSessionId;

                public GameSessionIdIndex(LoadoutHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class BySessionPlayerIndex : BTreeIndexBase<(ulong GameSessionId, ulong PlayerId)>
            {
                protected override (ulong GameSessionId, ulong PlayerId) GetKey(Loadout row) => (row.GameSessionId, row.PlayerId);

                public BySessionPlayerIndex(LoadoutHandle table) : base(table) { }
            }

            public readonly BySessionPlayerIndex BySessionPlayer;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Loadout row) => row.Id;

                public IdUniqueIndex(LoadoutHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Loadout row) => row.PlayerId;

                public PlayerIdIndex(LoadoutHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal LoadoutHandle(DbConnection conn) : base(conn)
            {
                GameSessionId = new(this);
                BySessionPlayer = new(this);
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(Loadout row) => row.Id;
        }

        public readonly LoadoutHandle Loadout;
    }

    public sealed class LoadoutCols
    {
        public global::SpacetimeDB.Col<Loadout, ulong> Id { get; }
        public global::SpacetimeDB.Col<Loadout, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<Loadout, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<Loadout, ulong> ArchetypeDefId { get; }
        public global::SpacetimeDB.Col<Loadout, ulong> WeaponDefId { get; }
        public global::SpacetimeDB.Col<Loadout, ulong> SkillDefId { get; }

        public LoadoutCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "game_session_id");
            PlayerId = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "player_id");
            ArchetypeDefId = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "archetype_def_id");
            WeaponDefId = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "weapon_def_id");
            SkillDefId = new global::SpacetimeDB.Col<Loadout, ulong>(tableName, "skill_def_id");
        }
    }

    public sealed class LoadoutIxCols
    {
        public global::SpacetimeDB.IxCol<Loadout, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Loadout, ulong> GameSessionId { get; }
        public global::SpacetimeDB.IxCol<Loadout, ulong> PlayerId { get; }

        public LoadoutIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Loadout, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<Loadout, ulong>(tableName, "game_session_id");
            PlayerId = new global::SpacetimeDB.IxCol<Loadout, ulong>(tableName, "player_id");
        }
    }
}
