// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapDefHandle : RemoteTableHandle<EventContext, MapDef>
        {
            protected override string RemoteTableName => "map_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MapDef row) => row.Id;

                public IdUniqueIndex(MapDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(MapDef row) => row.Name;

                public NameUniqueIndex(MapDefHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal MapDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(MapDef row) => row.Id;
        }

        public readonly MapDefHandle MapDef;
    }

    public sealed class MapDefCols
    {
        public global::SpacetimeDB.Col<MapDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<MapDef, string> Name { get; }
        public global::SpacetimeDB.Col<MapDef, float> SizeX { get; }
        public global::SpacetimeDB.Col<MapDef, float> SizeZ { get; }

        public MapDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MapDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<MapDef, string>(tableName, "name");
            SizeX = new global::SpacetimeDB.Col<MapDef, float>(tableName, "size_x");
            SizeZ = new global::SpacetimeDB.Col<MapDef, float>(tableName, "size_z");
        }
    }

    public sealed class MapDefIxCols
    {
        public global::SpacetimeDB.IxCol<MapDef, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<MapDef, string> Name { get; }

        public MapDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MapDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.IxCol<MapDef, string>(tableName, "name");
        }
    }
}
