// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapTerrainDefHandle : RemoteTableHandle<EventContext, MapTerrainDef>
        {
            protected override string RemoteTableName => "map_terrain_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MapTerrainDef row) => row.Id;

                public IdUniqueIndex(MapTerrainDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class MapDefIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MapTerrainDef row) => row.MapDefId;

                public MapDefIdIndex(MapTerrainDefHandle table) : base(table) { }
            }

            public readonly MapDefIdIndex MapDefId;

            internal MapTerrainDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                MapDefId = new(this);
            }

            protected override object GetPrimaryKey(MapTerrainDef row) => row.Id;
        }

        public readonly MapTerrainDefHandle MapTerrainDef;
    }

    public sealed class MapTerrainDefCols
    {
        public global::SpacetimeDB.Col<MapTerrainDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, ulong> MapDefId { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, TerrainType> TerrainType { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> PositionX { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> PositionY { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> PositionZ { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> RotationY { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, byte> TeamSlot { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> SizeX { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> SizeY { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, float> SizeZ { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, int> Armor { get; }
        public global::SpacetimeDB.Col<MapTerrainDef, bool> HasOutpostRegen { get; }

        public MapTerrainDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MapTerrainDef, ulong>(tableName, "id");
            MapDefId = new global::SpacetimeDB.Col<MapTerrainDef, ulong>(tableName, "map_def_id");
            TerrainType = new global::SpacetimeDB.Col<MapTerrainDef, TerrainType>(tableName, "terrain_type");
            PositionX = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "position_x");
            PositionY = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "position_y");
            PositionZ = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "position_z");
            RotationY = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "rotation_y");
            TeamSlot = new global::SpacetimeDB.Col<MapTerrainDef, byte>(tableName, "team_slot");
            SizeX = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "size_x");
            SizeY = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "size_y");
            SizeZ = new global::SpacetimeDB.Col<MapTerrainDef, float>(tableName, "size_z");
            MaxHealth = new global::SpacetimeDB.Col<MapTerrainDef, int>(tableName, "max_health");
            Armor = new global::SpacetimeDB.Col<MapTerrainDef, int>(tableName, "armor");
            HasOutpostRegen = new global::SpacetimeDB.Col<MapTerrainDef, bool>(tableName, "has_outpost_regen");
        }
    }

    public sealed class MapTerrainDefIxCols
    {
        public global::SpacetimeDB.IxCol<MapTerrainDef, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<MapTerrainDef, ulong> MapDefId { get; }

        public MapTerrainDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MapTerrainDef, ulong>(tableName, "id");
            MapDefId = new global::SpacetimeDB.IxCol<MapTerrainDef, ulong>(tableName, "map_def_id");
        }
    }
}
