// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MessageHandle : RemoteTableHandle<EventContext, Message>
        {
            protected override string RemoteTableName => "message";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Message row) => row.Id;

                public IdUniqueIndex(MessageHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SenderPlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Message row) => row.SenderPlayerId;

                public SenderPlayerIdIndex(MessageHandle table) : base(table) { }
            }

            public readonly SenderPlayerIdIndex SenderPlayerId;

            public sealed class SessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Message row) => row.SessionId;

                public SessionIdIndex(MessageHandle table) : base(table) { }
            }

            public readonly SessionIdIndex SessionId;

            internal MessageHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                SenderPlayerId = new(this);
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(Message row) => row.Id;
        }

        public readonly MessageHandle Message;
    }

    public sealed class MessageCols
    {
        public global::SpacetimeDB.Col<Message, ulong> Id { get; }
        public global::SpacetimeDB.Col<Message, string> Body { get; }
        public global::SpacetimeDB.Col<Message, ulong> SessionId { get; }
        public global::SpacetimeDB.Col<Message, ulong> SenderPlayerId { get; }
        public global::SpacetimeDB.Col<Message, bool> Deleted { get; }
        public global::SpacetimeDB.Col<Message, SpacetimeDB.Timestamp> TimeSent { get; }

        public MessageCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Message, ulong>(tableName, "id");
            Body = new global::SpacetimeDB.Col<Message, string>(tableName, "body");
            SessionId = new global::SpacetimeDB.Col<Message, ulong>(tableName, "session_id");
            SenderPlayerId = new global::SpacetimeDB.Col<Message, ulong>(tableName, "sender_player_id");
            Deleted = new global::SpacetimeDB.Col<Message, bool>(tableName, "deleted");
            TimeSent = new global::SpacetimeDB.Col<Message, SpacetimeDB.Timestamp>(tableName, "time_sent");
        }
    }

    public sealed class MessageIxCols
    {
        public global::SpacetimeDB.IxCol<Message, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Message, ulong> SessionId { get; }
        public global::SpacetimeDB.IxCol<Message, ulong> SenderPlayerId { get; }

        public MessageIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Message, ulong>(tableName, "id");
            SessionId = new global::SpacetimeDB.IxCol<Message, ulong>(tableName, "session_id");
            SenderPlayerId = new global::SpacetimeDB.IxCol<Message, ulong>(tableName, "sender_player_id");
        }
    }
}
