// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Player row) => row.Id;

                public IdUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Player row) => row.Name;

                public NameUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            public sealed class OwnerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.OwnerIdentity;

                public OwnerIdentityIndex(PlayerHandle table) : base(table) { }
            }

            public readonly OwnerIdentityIndex OwnerIdentity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Name = new(this);
                OwnerIdentity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Id;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, ulong> Id { get; }
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> OwnerIdentity { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> ControllerIdentity { get; }

        public PlayerCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Player, ulong>(tableName, "id");
            OwnerIdentity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "owner_identity");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            ControllerIdentity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "controller_identity");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> OwnerIdentity { get; }
        public global::SpacetimeDB.IxCol<Player, string> Name { get; }

        public PlayerIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Player, ulong>(tableName, "id");
            OwnerIdentity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "owner_identity");
            Name = new global::SpacetimeDB.IxCol<Player, string>(tableName, "name");
        }
    }
}
