// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProjectileHandle : RemoteTableHandle<EventContext, Projectile>
        {
            protected override string RemoteTableName => "projectile";

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Projectile row) => row.GameSessionId;

                public GameSessionIdIndex(ProjectileHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Projectile row) => row.Id;

                public IdUniqueIndex(ProjectileHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ProjectileHandle(DbConnection conn) : base(conn)
            {
                GameSessionId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(Projectile row) => row.Id;
        }

        public readonly ProjectileHandle Projectile;
    }

    public sealed class ProjectileCols
    {
        public global::SpacetimeDB.Col<Projectile, ulong> Id { get; }
        public global::SpacetimeDB.Col<Projectile, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<Projectile, ulong> CasterEntityId { get; }
        public global::SpacetimeDB.Col<Projectile, ulong> AbilityId { get; }
        public global::SpacetimeDB.Col<Projectile, DbVector3> Position { get; }
        public global::SpacetimeDB.Col<Projectile, float> DirectionX { get; }
        public global::SpacetimeDB.Col<Projectile, float> DirectionY { get; }
        public global::SpacetimeDB.Col<Projectile, float> DirectionZ { get; }
        public global::SpacetimeDB.Col<Projectile, float> Speed { get; }
        public global::SpacetimeDB.Col<Projectile, float> Radius { get; }
        public global::SpacetimeDB.Col<Projectile, float> MaxRange { get; }
        public global::SpacetimeDB.Col<Projectile, float> DistanceTraveled { get; }
        public global::SpacetimeDB.Col<Projectile, byte> CasterTeamSlot { get; }
        public global::SpacetimeDB.Col<Projectile, int> ResolvedPower { get; }
        public global::SpacetimeDB.Col<Projectile, bool> AllowSubSquadTargeting { get; }
        public global::SpacetimeDB.Col<Projectile, DamageDistribution> Distribution { get; }

        public ProjectileCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Projectile, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<Projectile, ulong>(tableName, "game_session_id");
            CasterEntityId = new global::SpacetimeDB.Col<Projectile, ulong>(tableName, "caster_entity_id");
            AbilityId = new global::SpacetimeDB.Col<Projectile, ulong>(tableName, "ability_id");
            Position = new global::SpacetimeDB.Col<Projectile, DbVector3>(tableName, "position");
            DirectionX = new global::SpacetimeDB.Col<Projectile, float>(tableName, "direction_x");
            DirectionY = new global::SpacetimeDB.Col<Projectile, float>(tableName, "direction_y");
            DirectionZ = new global::SpacetimeDB.Col<Projectile, float>(tableName, "direction_z");
            Speed = new global::SpacetimeDB.Col<Projectile, float>(tableName, "speed");
            Radius = new global::SpacetimeDB.Col<Projectile, float>(tableName, "radius");
            MaxRange = new global::SpacetimeDB.Col<Projectile, float>(tableName, "max_range");
            DistanceTraveled = new global::SpacetimeDB.Col<Projectile, float>(tableName, "distance_traveled");
            CasterTeamSlot = new global::SpacetimeDB.Col<Projectile, byte>(tableName, "caster_team_slot");
            ResolvedPower = new global::SpacetimeDB.Col<Projectile, int>(tableName, "resolved_power");
            AllowSubSquadTargeting = new global::SpacetimeDB.Col<Projectile, bool>(tableName, "allow_sub_squad_targeting");
            Distribution = new global::SpacetimeDB.Col<Projectile, DamageDistribution>(tableName, "distribution");
        }
    }

    public sealed class ProjectileIxCols
    {
        public global::SpacetimeDB.IxCol<Projectile, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Projectile, ulong> GameSessionId { get; }

        public ProjectileIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Projectile, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<Projectile, ulong>(tableName, "game_session_id");
        }
    }
}
