// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResupplySessionHandle : RemoteTableHandle<EventContext, ResupplySession>
        {
            protected override string RemoteTableName => "resupply_session";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ResupplySession row) => row.EntityId;

                public EntityIdUniqueIndex(ResupplySessionHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ResupplySessionHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ResupplySession row) => row.EntityId;
        }

        public readonly ResupplySessionHandle ResupplySession;
    }

    public sealed class ResupplySessionCols
    {
        public global::SpacetimeDB.Col<ResupplySession, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ResupplySession, ulong> BaseEntityId { get; }

        public ResupplySessionCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ResupplySession, ulong>(tableName, "entity_id");
            BaseEntityId = new global::SpacetimeDB.Col<ResupplySession, ulong>(tableName, "base_entity_id");
        }
    }

    public sealed class ResupplySessionIxCols
    {
        public global::SpacetimeDB.IxCol<ResupplySession, ulong> EntityId { get; }

        public ResupplySessionIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ResupplySession, ulong>(tableName, "entity_id");
        }
    }
}
