// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoadSegmentHandle : RemoteTableHandle<EventContext, RoadSegment>
        {
            protected override string RemoteTableName => "road_segment";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoadSegment row) => row.EntityId;

                public EntityIdUniqueIndex(RoadSegmentHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoadSegment row) => row.GameSessionId;

                public GameSessionIdIndex(RoadSegmentHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            internal RoadSegmentHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                GameSessionId = new(this);
            }

            protected override object GetPrimaryKey(RoadSegment row) => row.EntityId;
        }

        public readonly RoadSegmentHandle RoadSegment;
    }

    public sealed class RoadSegmentCols
    {
        public global::SpacetimeDB.Col<RoadSegment, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<RoadSegment, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<RoadSegment, byte> TeamSlot { get; }
        public global::SpacetimeDB.Col<RoadSegment, ulong> ConnectedToEntityId { get; }
        public global::SpacetimeDB.Col<RoadSegment, byte> Level { get; }

        public RoadSegmentCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<RoadSegment, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.Col<RoadSegment, ulong>(tableName, "game_session_id");
            TeamSlot = new global::SpacetimeDB.Col<RoadSegment, byte>(tableName, "team_slot");
            ConnectedToEntityId = new global::SpacetimeDB.Col<RoadSegment, ulong>(tableName, "connected_to_entity_id");
            Level = new global::SpacetimeDB.Col<RoadSegment, byte>(tableName, "level");
        }
    }

    public sealed class RoadSegmentIxCols
    {
        public global::SpacetimeDB.IxCol<RoadSegment, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<RoadSegment, ulong> GameSessionId { get; }

        public RoadSegmentIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<RoadSegment, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.IxCol<RoadSegment, ulong>(tableName, "game_session_id");
        }
    }
}
