// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SkillDefHandle : RemoteTableHandle<EventContext, SkillDef>
        {
            protected override string RemoteTableName => "skill_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SkillDef row) => row.Id;

                public IdUniqueIndex(SkillDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SkillDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SkillDef row) => row.Id;
        }

        public readonly SkillDefHandle SkillDef;
    }

    public sealed class SkillDefCols
    {
        public global::SpacetimeDB.Col<SkillDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<SkillDef, string> Name { get; }
        public global::SpacetimeDB.Col<SkillDef, string> Description { get; }
        public global::SpacetimeDB.Col<SkillDef, System.Collections.Generic.List<ulong>> AbilityIds { get; }

        public SkillDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SkillDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<SkillDef, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<SkillDef, string>(tableName, "description");
            AbilityIds = new global::SpacetimeDB.Col<SkillDef, System.Collections.Generic.List<ulong>>(tableName, "ability_ids");
        }
    }

    public sealed class SkillDefIxCols
    {
        public global::SpacetimeDB.IxCol<SkillDef, ulong> Id { get; }

        public SkillDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SkillDef, ulong>(tableName, "id");
        }
    }
}
