// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SoldierHandle : RemoteTableHandle<EventContext, Soldier>
        {
            protected override string RemoteTableName => "soldier";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Soldier row) => row.EntityId;

                public EntityIdUniqueIndex(SoldierHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal SoldierHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Soldier row) => row.EntityId;
        }

        public readonly SoldierHandle Soldier;
    }

    public sealed class SoldierCols
    {
        public global::SpacetimeDB.Col<Soldier, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Soldier, ulong> OwnerPlayerId { get; }
        public global::SpacetimeDB.Col<Soldier, byte> FormationIndex { get; }

        public SoldierCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Soldier, ulong>(tableName, "entity_id");
            OwnerPlayerId = new global::SpacetimeDB.Col<Soldier, ulong>(tableName, "owner_player_id");
            FormationIndex = new global::SpacetimeDB.Col<Soldier, byte>(tableName, "formation_index");
        }
    }

    public sealed class SoldierIxCols
    {
        public global::SpacetimeDB.IxCol<Soldier, ulong> EntityId { get; }

        public SoldierIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Soldier, ulong>(tableName, "entity_id");
        }
    }
}
