// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SquadHandle : RemoteTableHandle<EventContext, Squad>
        {
            protected override string RemoteTableName => "squad";

            public sealed class GamePlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Squad row) => row.GamePlayerId;

                public GamePlayerIdIndex(SquadHandle table) : base(table) { }
            }

            public readonly GamePlayerIdIndex GamePlayerId;

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Squad row) => row.GameSessionId;

                public GameSessionIdIndex(SquadHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Squad row) => row.Id;

                public IdUniqueIndex(SquadHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ParentSquadIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Squad row) => row.ParentSquadId;

                public ParentSquadIdIndex(SquadHandle table) : base(table) { }
            }

            public readonly ParentSquadIdIndex ParentSquadId;

            public sealed class SoldierIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Squad row) => row.SoldierId;

                public SoldierIdIndex(SquadHandle table) : base(table) { }
            }

            public readonly SoldierIdIndex SoldierId;

            internal SquadHandle(DbConnection conn) : base(conn)
            {
                GamePlayerId = new(this);
                GameSessionId = new(this);
                Id = new(this);
                ParentSquadId = new(this);
                SoldierId = new(this);
            }

            protected override object GetPrimaryKey(Squad row) => row.Id;
        }

        public readonly SquadHandle Squad;
    }

    public sealed class SquadCols
    {
        public global::SpacetimeDB.Col<Squad, ulong> Id { get; }
        public global::SpacetimeDB.Col<Squad, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<Squad, ulong> ParentSquadId { get; }
        public global::SpacetimeDB.Col<Squad, ulong> OwnerPlayerId { get; }
        public global::SpacetimeDB.Col<Squad, float> CohesionRadius { get; }
        public global::SpacetimeDB.Col<Squad, DbVector3> CenterPosition { get; }
        public global::SpacetimeDB.Col<Squad, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.Col<Squad, ulong> SoldierId { get; }

        public SquadCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "game_session_id");
            ParentSquadId = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "parent_squad_id");
            OwnerPlayerId = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "owner_player_id");
            CohesionRadius = new global::SpacetimeDB.Col<Squad, float>(tableName, "cohesion_radius");
            CenterPosition = new global::SpacetimeDB.Col<Squad, DbVector3>(tableName, "center_position");
            GamePlayerId = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "game_player_id");
            SoldierId = new global::SpacetimeDB.Col<Squad, ulong>(tableName, "soldier_id");
        }
    }

    public sealed class SquadIxCols
    {
        public global::SpacetimeDB.IxCol<Squad, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<Squad, ulong> GameSessionId { get; }
        public global::SpacetimeDB.IxCol<Squad, ulong> ParentSquadId { get; }
        public global::SpacetimeDB.IxCol<Squad, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.IxCol<Squad, ulong> SoldierId { get; }

        public SquadIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Squad, ulong>(tableName, "id");
            GameSessionId = new global::SpacetimeDB.IxCol<Squad, ulong>(tableName, "game_session_id");
            ParentSquadId = new global::SpacetimeDB.IxCol<Squad, ulong>(tableName, "parent_squad_id");
            GamePlayerId = new global::SpacetimeDB.IxCol<Squad, ulong>(tableName, "game_player_id");
            SoldierId = new global::SpacetimeDB.IxCol<Squad, ulong>(tableName, "soldier_id");
        }
    }
}
