// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeaponDefHandle : RemoteTableHandle<EventContext, WeaponDef>
        {
            protected override string RemoteTableName => "weapon_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WeaponDef row) => row.Id;

                public IdUniqueIndex(WeaponDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WeaponDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WeaponDef row) => row.Id;
        }

        public readonly WeaponDefHandle WeaponDef;
    }

    public sealed class WeaponDefCols
    {
        public global::SpacetimeDB.Col<WeaponDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<WeaponDef, string> Name { get; }
        public global::SpacetimeDB.Col<WeaponDef, string> Description { get; }
        public global::SpacetimeDB.Col<WeaponDef, ulong> PrimaryAbilityId { get; }
        public global::SpacetimeDB.Col<WeaponDef, bool> GrantsSupplies { get; }
        public global::SpacetimeDB.Col<WeaponDef, FireMode> Mode { get; }
        public global::SpacetimeDB.Col<WeaponDef, byte> PelletCount { get; }
        public global::SpacetimeDB.Col<WeaponDef, float> SpreadAngleDeg { get; }
        public global::SpacetimeDB.Col<WeaponDef, int> ClipSize { get; }
        public global::SpacetimeDB.Col<WeaponDef, ulong> ReloadTimeMs { get; }

        public WeaponDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WeaponDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<WeaponDef, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<WeaponDef, string>(tableName, "description");
            PrimaryAbilityId = new global::SpacetimeDB.Col<WeaponDef, ulong>(tableName, "primary_ability_id");
            GrantsSupplies = new global::SpacetimeDB.Col<WeaponDef, bool>(tableName, "grants_supplies");
            Mode = new global::SpacetimeDB.Col<WeaponDef, FireMode>(tableName, "mode");
            PelletCount = new global::SpacetimeDB.Col<WeaponDef, byte>(tableName, "pellet_count");
            SpreadAngleDeg = new global::SpacetimeDB.Col<WeaponDef, float>(tableName, "spread_angle_deg");
            ClipSize = new global::SpacetimeDB.Col<WeaponDef, int>(tableName, "clip_size");
            ReloadTimeMs = new global::SpacetimeDB.Col<WeaponDef, ulong>(tableName, "reload_time_ms");
        }
    }

    public sealed class WeaponDefIxCols
    {
        public global::SpacetimeDB.IxCol<WeaponDef, ulong> Id { get; }

        public WeaponDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WeaponDef, ulong>(tableName, "id");
        }
    }
}
