// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeaponStateHandle : RemoteTableHandle<EventContext, WeaponState>
        {
            protected override string RemoteTableName => "weapon_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WeaponState row) => row.EntityId;

                public EntityIdUniqueIndex(WeaponStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal WeaponStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(WeaponState row) => row.EntityId;
        }

        public readonly WeaponStateHandle WeaponState;
    }

    public sealed class WeaponStateCols
    {
        public global::SpacetimeDB.Col<WeaponState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<WeaponState, int> AmmoInClip { get; }
        public global::SpacetimeDB.Col<WeaponState, SpacetimeDB.Timestamp> ReloadingUntil { get; }

        public WeaponStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<WeaponState, ulong>(tableName, "entity_id");
            AmmoInClip = new global::SpacetimeDB.Col<WeaponState, int>(tableName, "ammo_in_clip");
            ReloadingUntil = new global::SpacetimeDB.Col<WeaponState, SpacetimeDB.Timestamp>(tableName, "reloading_until");
        }
    }

    public sealed class WeaponStateIxCols
    {
        public global::SpacetimeDB.IxCol<WeaponState, ulong> EntityId { get; }

        public WeaponStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<WeaponState, ulong>(tableName, "entity_id");
        }
    }
}
