// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ArchetypeDefHandle : RemoteTableHandle<EventContext, ArchetypeDef>
        {
            protected override string RemoteTableName => "archetype_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ArchetypeDef row) => row.Id;

                public IdUniqueIndex(ArchetypeDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ArchetypeDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ArchetypeDef row) => row.Id;
        }

        public readonly ArchetypeDefHandle ArchetypeDef;
    }

    public sealed class ArchetypeDefCols
    {
        public global::SpacetimeDB.Col<ArchetypeDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, string> Name { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, string> Description { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, ArchetypeKind> Kind { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, int> BonusHealth { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, int> BonusArmor { get; }
        public global::SpacetimeDB.Col<ArchetypeDef, System.Collections.Generic.List<ulong>> InnateAbilityIds { get; }

        public ArchetypeDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ArchetypeDef, ulong>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ArchetypeDef, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<ArchetypeDef, string>(tableName, "description");
            Kind = new global::SpacetimeDB.Col<ArchetypeDef, ArchetypeKind>(tableName, "kind");
            BonusHealth = new global::SpacetimeDB.Col<ArchetypeDef, int>(tableName, "bonus_health");
            BonusArmor = new global::SpacetimeDB.Col<ArchetypeDef, int>(tableName, "bonus_armor");
            InnateAbilityIds = new global::SpacetimeDB.Col<ArchetypeDef, System.Collections.Generic.List<ulong>>(tableName, "innate_ability_ids");
        }
    }

    public sealed class ArchetypeDefIxCols
    {
        public global::SpacetimeDB.IxCol<ArchetypeDef, ulong> Id { get; }

        public ArchetypeDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ArchetypeDef, ulong>(tableName, "id");
        }
    }
}
