// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseResourceStoreHandle : RemoteTableHandle<EventContext, BaseResourceStore>
        {
            protected override string RemoteTableName => "base_resource_store";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BaseResourceStore row) => row.EntityId;

                public EntityIdUniqueIndex(BaseResourceStoreHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(BaseResourceStore row) => row.GameSessionId;

                public GameSessionIdIndex(BaseResourceStoreHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            internal BaseResourceStoreHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                GameSessionId = new(this);
            }

            protected override object GetPrimaryKey(BaseResourceStore row) => row.EntityId;
        }

        public readonly BaseResourceStoreHandle BaseResourceStore;
    }

    public sealed class BaseResourceStoreCols
    {
        public global::SpacetimeDB.Col<BaseResourceStore, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, byte> TeamSlot { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, int> Supplies { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, int> SuppliesMax { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, float> GenerationPerSecond { get; }
        public global::SpacetimeDB.Col<BaseResourceStore, byte> Level { get; }

        public BaseResourceStoreCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<BaseResourceStore, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.Col<BaseResourceStore, ulong>(tableName, "game_session_id");
            TeamSlot = new global::SpacetimeDB.Col<BaseResourceStore, byte>(tableName, "team_slot");
            Supplies = new global::SpacetimeDB.Col<BaseResourceStore, int>(tableName, "supplies");
            SuppliesMax = new global::SpacetimeDB.Col<BaseResourceStore, int>(tableName, "supplies_max");
            GenerationPerSecond = new global::SpacetimeDB.Col<BaseResourceStore, float>(tableName, "generation_per_second");
            Level = new global::SpacetimeDB.Col<BaseResourceStore, byte>(tableName, "level");
        }
    }

    public sealed class BaseResourceStoreIxCols
    {
        public global::SpacetimeDB.IxCol<BaseResourceStore, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<BaseResourceStore, ulong> GameSessionId { get; }

        public BaseResourceStoreIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<BaseResourceStore, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.IxCol<BaseResourceStore, ulong>(tableName, "game_session_id");
        }
    }
}
