// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CapturePointHandle : RemoteTableHandle<EventContext, CapturePoint>
        {
            protected override string RemoteTableName => "capture_point";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CapturePoint row) => row.EntityId;

                public EntityIdUniqueIndex(CapturePointHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal CapturePointHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(CapturePoint row) => row.EntityId;
        }

        public readonly CapturePointHandle CapturePoint;
    }

    public sealed class CapturePointCols
    {
        public global::SpacetimeDB.Col<CapturePoint, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<CapturePoint, float> Radius { get; }
        public global::SpacetimeDB.Col<CapturePoint, byte> OwningTeam { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> InfluenceTeam1 { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> InfluenceTeam2 { get; }
        public global::SpacetimeDB.Col<CapturePoint, int> MaxInfluence { get; }

        public CapturePointCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<CapturePoint, ulong>(tableName, "entity_id");
            Radius = new global::SpacetimeDB.Col<CapturePoint, float>(tableName, "radius");
            OwningTeam = new global::SpacetimeDB.Col<CapturePoint, byte>(tableName, "owning_team");
            InfluenceTeam1 = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "influence_team_1");
            InfluenceTeam2 = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "influence_team_2");
            MaxInfluence = new global::SpacetimeDB.Col<CapturePoint, int>(tableName, "max_influence");
        }
    }

    public sealed class CapturePointIxCols
    {
        public global::SpacetimeDB.IxCol<CapturePoint, ulong> EntityId { get; }

        public CapturePointIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<CapturePoint, ulong>(tableName, "entity_id");
        }
    }
}
