// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CorpseHandle : RemoteTableHandle<EventContext, Corpse>
        {
            protected override string RemoteTableName => "corpse";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Corpse row) => row.EntityId;

                public EntityIdUniqueIndex(CorpseHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal CorpseHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Corpse row) => row.EntityId;
        }

        public readonly CorpseHandle Corpse;
    }

    public sealed class CorpseCols
    {
        public global::SpacetimeDB.Col<Corpse, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Corpse, ulong> SourceEntityId { get; }
        public global::SpacetimeDB.Col<Corpse, ulong> PlayerId { get; }

        public CorpseCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "entity_id");
            SourceEntityId = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "source_entity_id");
            PlayerId = new global::SpacetimeDB.Col<Corpse, ulong>(tableName, "player_id");
        }
    }

    public sealed class CorpseIxCols
    {
        public global::SpacetimeDB.IxCol<Corpse, ulong> EntityId { get; }

        public CorpseIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Corpse, ulong>(tableName, "entity_id");
        }
    }
}
