// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EntityHandle : RemoteTableHandle<EventContext, Entity>
        {
            protected override string RemoteTableName => "entity";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Entity row) => row.EntityId;

                public EntityIdUniqueIndex(EntityHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class GameSessionIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(Entity row) => row.GameSessionId;

                public GameSessionIdIndex(EntityHandle table) : base(table) { }
            }

            public readonly GameSessionIdIndex GameSessionId;

            internal EntityHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                GameSessionId = new(this);
            }

            protected override object GetPrimaryKey(Entity row) => row.EntityId;
        }

        public readonly EntityHandle Entity;
    }

    public sealed class EntityCols
    {
        public global::SpacetimeDB.Col<Entity, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Entity, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<Entity, EntityType> Type { get; }
        public global::SpacetimeDB.Col<Entity, DbVector3> Position { get; }
        public global::SpacetimeDB.Col<Entity, float> RotationY { get; }
        public global::SpacetimeDB.Col<Entity, byte> TeamSlot { get; }

        public EntityCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Entity, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.Col<Entity, ulong>(tableName, "game_session_id");
            Type = new global::SpacetimeDB.Col<Entity, EntityType>(tableName, "type");
            Position = new global::SpacetimeDB.Col<Entity, DbVector3>(tableName, "position");
            RotationY = new global::SpacetimeDB.Col<Entity, float>(tableName, "rotation_y");
            TeamSlot = new global::SpacetimeDB.Col<Entity, byte>(tableName, "team_slot");
        }
    }

    public sealed class EntityIxCols
    {
        public global::SpacetimeDB.IxCol<Entity, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<Entity, ulong> GameSessionId { get; }

        public EntityIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Entity, ulong>(tableName, "entity_id");
            GameSessionId = new global::SpacetimeDB.IxCol<Entity, ulong>(tableName, "game_session_id");
        }
    }
}
