// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameSessionHandle : RemoteTableHandle<EventContext, GameSession>
        {
            protected override string RemoteTableName => "game_session";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GameSession row) => row.Id;

                public IdUniqueIndex(GameSessionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class OwnerIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(GameSession row) => row.OwnerIdentity;

                public OwnerIdentityIndex(GameSessionHandle table) : base(table) { }
            }

            public readonly OwnerIdentityIndex OwnerIdentity;

            internal GameSessionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                OwnerIdentity = new(this);
            }

            protected override object GetPrimaryKey(GameSession row) => row.Id;
        }

        public readonly GameSessionHandle GameSession;
    }

    public sealed class GameSessionCols
    {
        public global::SpacetimeDB.Col<GameSession, ulong> Id { get; }
        public global::SpacetimeDB.Col<GameSession, SpacetimeDB.Identity> OwnerIdentity { get; }
        public global::SpacetimeDB.Col<GameSession, SessionState> State { get; }
        public global::SpacetimeDB.Col<GameSession, uint> MaxPlayers { get; }
        public global::SpacetimeDB.Col<GameSession, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<GameSession, ulong> MapDefId { get; }
        public global::SpacetimeDB.Col<GameSession, uint> RespawnTimerSeconds { get; }
        public global::SpacetimeDB.NullableCol<GameSession, byte> WinnerTeamSlot { get; }

        public GameSessionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameSession, ulong>(tableName, "id");
            OwnerIdentity = new global::SpacetimeDB.Col<GameSession, SpacetimeDB.Identity>(tableName, "owner_identity");
            State = new global::SpacetimeDB.Col<GameSession, SessionState>(tableName, "state");
            MaxPlayers = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "max_players");
            CreatedAt = new global::SpacetimeDB.Col<GameSession, SpacetimeDB.Timestamp>(tableName, "created_at");
            MapDefId = new global::SpacetimeDB.Col<GameSession, ulong>(tableName, "map_def_id");
            RespawnTimerSeconds = new global::SpacetimeDB.Col<GameSession, uint>(tableName, "respawn_timer_seconds");
            WinnerTeamSlot = new global::SpacetimeDB.NullableCol<GameSession, byte>(tableName, "winner_team_slot");
        }
    }

    public sealed class GameSessionIxCols
    {
        public global::SpacetimeDB.IxCol<GameSession, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<GameSession, SpacetimeDB.Identity> OwnerIdentity { get; }

        public GameSessionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameSession, ulong>(tableName, "id");
            OwnerIdentity = new global::SpacetimeDB.IxCol<GameSession, SpacetimeDB.Identity>(tableName, "owner_identity");
        }
    }
}
