// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MapCapturePointDefHandle : RemoteTableHandle<EventContext, MapCapturePointDef>
        {
            protected override string RemoteTableName => "map_capture_point_def";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MapCapturePointDef row) => row.Id;

                public IdUniqueIndex(MapCapturePointDefHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class MapDefIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MapCapturePointDef row) => row.MapDefId;

                public MapDefIdIndex(MapCapturePointDefHandle table) : base(table) { }
            }

            public readonly MapDefIdIndex MapDefId;

            internal MapCapturePointDefHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                MapDefId = new(this);
            }

            protected override object GetPrimaryKey(MapCapturePointDef row) => row.Id;
        }

        public readonly MapCapturePointDefHandle MapCapturePointDef;
    }

    public sealed class MapCapturePointDefCols
    {
        public global::SpacetimeDB.Col<MapCapturePointDef, ulong> Id { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, ulong> MapDefId { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, float> PositionX { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, float> PositionY { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, float> PositionZ { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, float> Radius { get; }
        public global::SpacetimeDB.Col<MapCapturePointDef, int> MaxInfluence { get; }

        public MapCapturePointDefCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MapCapturePointDef, ulong>(tableName, "id");
            MapDefId = new global::SpacetimeDB.Col<MapCapturePointDef, ulong>(tableName, "map_def_id");
            PositionX = new global::SpacetimeDB.Col<MapCapturePointDef, float>(tableName, "position_x");
            PositionY = new global::SpacetimeDB.Col<MapCapturePointDef, float>(tableName, "position_y");
            PositionZ = new global::SpacetimeDB.Col<MapCapturePointDef, float>(tableName, "position_z");
            Radius = new global::SpacetimeDB.Col<MapCapturePointDef, float>(tableName, "radius");
            MaxInfluence = new global::SpacetimeDB.Col<MapCapturePointDef, int>(tableName, "max_influence");
        }
    }

    public sealed class MapCapturePointDefIxCols
    {
        public global::SpacetimeDB.IxCol<MapCapturePointDef, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<MapCapturePointDef, ulong> MapDefId { get; }

        public MapCapturePointDefIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MapCapturePointDef, ulong>(tableName, "id");
            MapDefId = new global::SpacetimeDB.IxCol<MapCapturePointDef, ulong>(tableName, "map_def_id");
        }
    }
}
