// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PositionOverrideHandle : RemoteTableHandle<EventContext, PositionOverride>
        {
            protected override string RemoteTableName => "position_override";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PositionOverride row) => row.Id;

                public IdUniqueIndex(PositionOverrideHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PositionOverride row) => row.PlayerId;

                public PlayerIdIndex(PositionOverrideHandle table) : base(table) { }
            }

            public readonly PlayerIdIndex PlayerId;

            internal PositionOverrideHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(PositionOverride row) => row.Id;
        }

        public readonly PositionOverrideHandle PositionOverride;
    }

    public sealed class PositionOverrideCols
    {
        public global::SpacetimeDB.Col<PositionOverride, ulong> Id { get; }
        public global::SpacetimeDB.Col<PositionOverride, ulong> PlayerId { get; }
        public global::SpacetimeDB.Col<PositionOverride, ulong> GameSessionId { get; }
        public global::SpacetimeDB.Col<PositionOverride, DbVector3> Position { get; }

        public PositionOverrideCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PositionOverride, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.Col<PositionOverride, ulong>(tableName, "player_id");
            GameSessionId = new global::SpacetimeDB.Col<PositionOverride, ulong>(tableName, "game_session_id");
            Position = new global::SpacetimeDB.Col<PositionOverride, DbVector3>(tableName, "position");
        }
    }

    public sealed class PositionOverrideIxCols
    {
        public global::SpacetimeDB.IxCol<PositionOverride, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<PositionOverride, ulong> PlayerId { get; }

        public PositionOverrideIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PositionOverride, ulong>(tableName, "id");
            PlayerId = new global::SpacetimeDB.IxCol<PositionOverride, ulong>(tableName, "player_id");
        }
    }
}
