// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourcePoolHandle : RemoteTableHandle<EventContext, ResourcePool>
        {
            protected override string RemoteTableName => "resource_pool";

            public sealed class EntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ResourcePool row) => row.EntityId;

                public EntityIdIndex(ResourcePoolHandle table) : base(table) { }
            }

            public readonly EntityIdIndex EntityId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ResourcePool row) => row.Id;

                public IdUniqueIndex(ResourcePoolHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ResourcePoolHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ResourcePool row) => row.Id;
        }

        public readonly ResourcePoolHandle ResourcePool;
    }

    public sealed class ResourcePoolCols
    {
        public global::SpacetimeDB.Col<ResourcePool, ulong> Id { get; }
        public global::SpacetimeDB.Col<ResourcePool, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ResourcePool, ResourceKind> Kind { get; }
        public global::SpacetimeDB.Col<ResourcePool, float> Current { get; }
        public global::SpacetimeDB.Col<ResourcePool, float> Max { get; }

        public ResourcePoolCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ResourcePool, ulong>(tableName, "id");
            EntityId = new global::SpacetimeDB.Col<ResourcePool, ulong>(tableName, "entity_id");
            Kind = new global::SpacetimeDB.Col<ResourcePool, ResourceKind>(tableName, "kind");
            Current = new global::SpacetimeDB.Col<ResourcePool, float>(tableName, "current");
            Max = new global::SpacetimeDB.Col<ResourcePool, float>(tableName, "max");
        }
    }

    public sealed class ResourcePoolIxCols
    {
        public global::SpacetimeDB.IxCol<ResourcePool, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ResourcePool, ulong> EntityId { get; }

        public ResourcePoolIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ResourcePool, ulong>(tableName, "id");
            EntityId = new global::SpacetimeDB.IxCol<ResourcePool, ulong>(tableName, "entity_id");
        }
    }
}
