// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TargetableHandle : RemoteTableHandle<EventContext, Targetable>
        {
            protected override string RemoteTableName => "targetable";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Targetable row) => row.EntityId;

                public EntityIdUniqueIndex(TargetableHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TargetableHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Targetable row) => row.EntityId;
        }

        public readonly TargetableHandle Targetable;
    }

    public sealed class TargetableCols
    {
        public global::SpacetimeDB.Col<Targetable, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<Targetable, int> Health { get; }
        public global::SpacetimeDB.Col<Targetable, int> MaxHealth { get; }
        public global::SpacetimeDB.Col<Targetable, int> Armor { get; }
        public global::SpacetimeDB.Col<Targetable, bool> Dead { get; }
        public global::SpacetimeDB.NullableCol<Targetable, SpacetimeDB.Timestamp> DiedAt { get; }

        public TargetableCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<Targetable, ulong>(tableName, "entity_id");
            Health = new global::SpacetimeDB.Col<Targetable, int>(tableName, "health");
            MaxHealth = new global::SpacetimeDB.Col<Targetable, int>(tableName, "max_health");
            Armor = new global::SpacetimeDB.Col<Targetable, int>(tableName, "armor");
            Dead = new global::SpacetimeDB.Col<Targetable, bool>(tableName, "dead");
            DiedAt = new global::SpacetimeDB.NullableCol<Targetable, SpacetimeDB.Timestamp>(tableName, "died_at");
        }
    }

    public sealed class TargetableIxCols
    {
        public global::SpacetimeDB.IxCol<Targetable, ulong> EntityId { get; }

        public TargetableIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<Targetable, ulong>(tableName, "entity_id");
        }
    }
}
