// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TerrainFeatureHandle : RemoteTableHandle<EventContext, TerrainFeature>
        {
            protected override string RemoteTableName => "terrain_feature";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TerrainFeature row) => row.EntityId;

                public EntityIdUniqueIndex(TerrainFeatureHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TerrainFeatureHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(TerrainFeature row) => row.EntityId;
        }

        public readonly TerrainFeatureHandle TerrainFeature;
    }

    public sealed class TerrainFeatureCols
    {
        public global::SpacetimeDB.Col<TerrainFeature, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<TerrainFeature, TerrainType> Type { get; }
        public global::SpacetimeDB.Col<TerrainFeature, float> SizeX { get; }
        public global::SpacetimeDB.Col<TerrainFeature, float> SizeY { get; }
        public global::SpacetimeDB.Col<TerrainFeature, float> SizeZ { get; }
        public global::SpacetimeDB.NullableCol<TerrainFeature, ulong> CasterEntityId { get; }
        public global::SpacetimeDB.NullableCol<TerrainFeature, SpacetimeDB.Timestamp> ExpiresAt { get; }
        public global::SpacetimeDB.Col<TerrainFeature, bool> Expired { get; }

        public TerrainFeatureCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<TerrainFeature, ulong>(tableName, "entity_id");
            Type = new global::SpacetimeDB.Col<TerrainFeature, TerrainType>(tableName, "type");
            SizeX = new global::SpacetimeDB.Col<TerrainFeature, float>(tableName, "size_x");
            SizeY = new global::SpacetimeDB.Col<TerrainFeature, float>(tableName, "size_y");
            SizeZ = new global::SpacetimeDB.Col<TerrainFeature, float>(tableName, "size_z");
            CasterEntityId = new global::SpacetimeDB.NullableCol<TerrainFeature, ulong>(tableName, "caster_entity_id");
            ExpiresAt = new global::SpacetimeDB.NullableCol<TerrainFeature, SpacetimeDB.Timestamp>(tableName, "expires_at");
            Expired = new global::SpacetimeDB.Col<TerrainFeature, bool>(tableName, "expired");
        }
    }

    public sealed class TerrainFeatureIxCols
    {
        public global::SpacetimeDB.IxCol<TerrainFeature, ulong> EntityId { get; }

        public TerrainFeatureIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<TerrainFeature, ulong>(tableName, "entity_id");
        }
    }
}
