// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "type")]
        public AbilityType Type;
        [DataMember(Name = "valid_targets")]
        public System.Collections.Generic.List<TargetType> ValidTargets;
        [DataMember(Name = "base_power")]
        public int BasePower;
        [DataMember(Name = "base_range")]
        public float BaseRange;
        [DataMember(Name = "base_radius")]
        public float BaseRadius;
        [DataMember(Name = "cooldown_ms")]
        public ulong CooldownMs;
        [DataMember(Name = "resource_costs")]
        public System.Collections.Generic.List<ResourceCost> ResourceCosts;
        [DataMember(Name = "granted_mods")]
        public System.Collections.Generic.List<AbilityMod> GrantedMods;
        [DataMember(Name = "effect_duration_ms")]
        public ulong EffectDurationMs;
        [DataMember(Name = "affected_ability_ids")]
        public System.Collections.Generic.List<ulong> AffectedAbilityIds;
        [DataMember(Name = "spawned_terrain_type")]
        public TerrainType? SpawnedTerrainType;
        [DataMember(Name = "terrain_size_x")]
        public float TerrainSizeX;
        [DataMember(Name = "terrain_size_y")]
        public float TerrainSizeY;
        [DataMember(Name = "terrain_size_z")]
        public float TerrainSizeZ;
        [DataMember(Name = "terrain_max_health")]
        public int TerrainMaxHealth;
        [DataMember(Name = "distribution")]
        public DamageDistribution Distribution;
        [DataMember(Name = "allow_sub_squad_targeting")]
        public bool AllowSubSquadTargeting;
        [DataMember(Name = "targeting")]
        public TargetingMode Targeting;
        [DataMember(Name = "projectile_speed")]
        public float ProjectileSpeed;
        [DataMember(Name = "drop_rate")]
        public float DropRate;

        public AbilityDef(
            ulong Id,
            string Name,
            string Description,
            AbilityType Type,
            System.Collections.Generic.List<TargetType> ValidTargets,
            int BasePower,
            float BaseRange,
            float BaseRadius,
            ulong CooldownMs,
            System.Collections.Generic.List<ResourceCost> ResourceCosts,
            System.Collections.Generic.List<AbilityMod> GrantedMods,
            ulong EffectDurationMs,
            System.Collections.Generic.List<ulong> AffectedAbilityIds,
            TerrainType? SpawnedTerrainType,
            float TerrainSizeX,
            float TerrainSizeY,
            float TerrainSizeZ,
            int TerrainMaxHealth,
            DamageDistribution Distribution,
            bool AllowSubSquadTargeting,
            TargetingMode Targeting,
            float ProjectileSpeed,
            float DropRate
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Type = Type;
            this.ValidTargets = ValidTargets;
            this.BasePower = BasePower;
            this.BaseRange = BaseRange;
            this.BaseRadius = BaseRadius;
            this.CooldownMs = CooldownMs;
            this.ResourceCosts = ResourceCosts;
            this.GrantedMods = GrantedMods;
            this.EffectDurationMs = EffectDurationMs;
            this.AffectedAbilityIds = AffectedAbilityIds;
            this.SpawnedTerrainType = SpawnedTerrainType;
            this.TerrainSizeX = TerrainSizeX;
            this.TerrainSizeY = TerrainSizeY;
            this.TerrainSizeZ = TerrainSizeZ;
            this.TerrainMaxHealth = TerrainMaxHealth;
            this.Distribution = Distribution;
            this.AllowSubSquadTargeting = AllowSubSquadTargeting;
            this.Targeting = Targeting;
            this.ProjectileSpeed = ProjectileSpeed;
            this.DropRate = DropRate;
        }

        public AbilityDef()
        {
            this.Name = "";
            this.Description = "";
            this.ValidTargets = new();
            this.ResourceCosts = new();
            this.GrantedMods = new();
            this.AffectedAbilityIds = new();
        }
    }
}
