// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseResourceStore
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;
        [DataMember(Name = "supplies")]
        public int Supplies;
        [DataMember(Name = "supplies_max")]
        public int SuppliesMax;
        [DataMember(Name = "generation_per_second")]
        public float GenerationPerSecond;
        [DataMember(Name = "level")]
        public byte Level;

        public BaseResourceStore(
            ulong EntityId,
            ulong GameSessionId,
            byte TeamSlot,
            int Supplies,
            int SuppliesMax,
            float GenerationPerSecond,
            byte Level
        )
        {
            this.EntityId = EntityId;
            this.GameSessionId = GameSessionId;
            this.TeamSlot = TeamSlot;
            this.Supplies = Supplies;
            this.SuppliesMax = SuppliesMax;
            this.GenerationPerSecond = GenerationPerSecond;
            this.Level = Level;
        }

        public BaseResourceStore()
        {
        }
    }
}
