// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BattleLogEntry
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "occurred_at")]
        public SpacetimeDB.Timestamp OccurredAt;
        [DataMember(Name = "event_type")]
        public BattleLogEventType EventType;
        [DataMember(Name = "actor_entity_id")]
        public ulong ActorEntityId;
        [DataMember(Name = "ability_id")]
        public ulong? AbilityId;
        [DataMember(Name = "target_entity_ids")]
        public System.Collections.Generic.List<ulong> TargetEntityIds;
        [DataMember(Name = "resolved_power")]
        public int ResolvedPower;

        public BattleLogEntry(
            ulong Id,
            ulong GameSessionId,
            SpacetimeDB.Timestamp OccurredAt,
            BattleLogEventType EventType,
            ulong ActorEntityId,
            ulong? AbilityId,
            System.Collections.Generic.List<ulong> TargetEntityIds,
            int ResolvedPower
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.OccurredAt = OccurredAt;
            this.EventType = EventType;
            this.ActorEntityId = ActorEntityId;
            this.AbilityId = AbilityId;
            this.TargetEntityIds = TargetEntityIds;
            this.ResolvedPower = ResolvedPower;
        }

        public BattleLogEntry()
        {
            this.TargetEntityIds = new();
        }
    }
}
