// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CapturePoint
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "owning_team")]
        public byte OwningTeam;
        [DataMember(Name = "influence_team_1")]
        public int InfluenceTeam1;
        [DataMember(Name = "influence_team_2")]
        public int InfluenceTeam2;
        [DataMember(Name = "max_influence")]
        public int MaxInfluence;

        public CapturePoint(
            ulong EntityId,
            float Radius,
            byte OwningTeam,
            int InfluenceTeam1,
            int InfluenceTeam2,
            int MaxInfluence
        )
        {
            this.EntityId = EntityId;
            this.Radius = Radius;
            this.OwningTeam = OwningTeam;
            this.InfluenceTeam1 = InfluenceTeam1;
            this.InfluenceTeam2 = InfluenceTeam2;
            this.MaxInfluence = MaxInfluence;
        }

        public CapturePoint()
        {
        }
    }
}
