// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Corpse
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "source_entity_id")]
        public ulong? SourceEntityId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;

        public Corpse(
            ulong EntityId,
            ulong? SourceEntityId,
            ulong PlayerId
        )
        {
            this.EntityId = EntityId;
            this.SourceEntityId = SourceEntityId;
            this.PlayerId = PlayerId;
        }

        public Corpse()
        {
        }
    }
}
