// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameSession
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "state")]
        public SessionState State;
        [DataMember(Name = "max_players")]
        public uint MaxPlayers;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "map_def_id")]
        public ulong MapDefId;
        [DataMember(Name = "respawn_timer_seconds")]
        public uint RespawnTimerSeconds;
        [DataMember(Name = "winner_team_slot")]
        public byte? WinnerTeamSlot;

        public GameSession(
            ulong Id,
            SpacetimeDB.Identity OwnerIdentity,
            SessionState State,
            uint MaxPlayers,
            SpacetimeDB.Timestamp CreatedAt,
            ulong MapDefId,
            uint RespawnTimerSeconds,
            byte? WinnerTeamSlot
        )
        {
            this.Id = Id;
            this.OwnerIdentity = OwnerIdentity;
            this.State = State;
            this.MaxPlayers = MaxPlayers;
            this.CreatedAt = CreatedAt;
            this.MapDefId = MapDefId;
            this.RespawnTimerSeconds = RespawnTimerSeconds;
            this.WinnerTeamSlot = WinnerTeamSlot;
        }

        public GameSession()
        {
        }
    }
}
