// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapCapturePointDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "map_def_id")]
        public ulong MapDefId;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "position_z")]
        public float PositionZ;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "max_influence")]
        public int MaxInfluence;

        public MapCapturePointDef(
            ulong Id,
            ulong MapDefId,
            float PositionX,
            float PositionY,
            float PositionZ,
            float Radius,
            int MaxInfluence
        )
        {
            this.Id = Id;
            this.MapDefId = MapDefId;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.PositionZ = PositionZ;
            this.Radius = Radius;
            this.MaxInfluence = MaxInfluence;
        }

        public MapCapturePointDef()
        {
        }
    }
}
