// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "size_x")]
        public float SizeX;
        [DataMember(Name = "size_z")]
        public float SizeZ;

        public MapDef(
            ulong Id,
            string Name,
            float SizeX,
            float SizeZ
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.SizeX = SizeX;
            this.SizeZ = SizeZ;
        }

        public MapDef()
        {
            this.Name = "";
        }
    }
}
