// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResupplySession
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "base_entity_id")]
        public ulong BaseEntityId;

        public ResupplySession(
            ulong EntityId,
            ulong BaseEntityId
        )
        {
            this.EntityId = EntityId;
            this.BaseEntityId = BaseEntityId;
        }

        public ResupplySession()
        {
        }
    }
}
