// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SoldierCombatTickSchedule
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;

        public SoldierCombatTickSchedule(
            ulong Id,
            ulong GameSessionId,
            SpacetimeDB.ScheduleAt ScheduledAt
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.ScheduledAt = ScheduledAt;
        }

        public SoldierCombatTickSchedule()
        {
            this.ScheduledAt = null!;
        }
    }
}
