// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Targetable
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "armor")]
        public int Armor;
        [DataMember(Name = "dead")]
        public bool Dead;
        [DataMember(Name = "died_at")]
        public SpacetimeDB.Timestamp? DiedAt;

        public Targetable(
            ulong EntityId,
            int Health,
            int MaxHealth,
            int Armor,
            bool Dead,
            SpacetimeDB.Timestamp? DiedAt
        )
        {
            this.EntityId = EntityId;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.Armor = Armor;
            this.Dead = Dead;
            this.DiedAt = DiedAt;
        }

        public Targetable()
        {
        }
    }
}
