// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TerrainFeature
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "type")]
        public TerrainType Type;
        [DataMember(Name = "size_x")]
        public float SizeX;
        [DataMember(Name = "size_y")]
        public float SizeY;
        [DataMember(Name = "size_z")]
        public float SizeZ;
        [DataMember(Name = "caster_entity_id")]
        public ulong? CasterEntityId;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp? ExpiresAt;
        [DataMember(Name = "expired")]
        public bool Expired;

        public TerrainFeature(
            ulong EntityId,
            TerrainType Type,
            float SizeX,
            float SizeY,
            float SizeZ,
            ulong? CasterEntityId,
            SpacetimeDB.Timestamp? ExpiresAt,
            bool Expired
        )
        {
            this.EntityId = EntityId;
            this.Type = Type;
            this.SizeX = SizeX;
            this.SizeY = SizeY;
            this.SizeZ = SizeZ;
            this.CasterEntityId = CasterEntityId;
            this.ExpiresAt = ExpiresAt;
            this.Expired = Expired;
        }

        public TerrainFeature()
        {
        }
    }
}
