// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "ammo_in_clip")]
        public int AmmoInClip;
        [DataMember(Name = "reloading_until")]
        public SpacetimeDB.Timestamp? ReloadingUntil;

        public WeaponState(
            ulong EntityId,
            int AmmoInClip,
            SpacetimeDB.Timestamp? ReloadingUntil
        )
        {
            this.EntityId = EntityId;
            this.AmmoInClip = AmmoInClip;
            this.ReloadingUntil = ReloadingUntil;
        }

        public WeaponState()
        {
        }
    }
}
