# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client

func clear_data(cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('clear_data', [], [])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. name: String [br]
func create_chat_session(name: String, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('create_chat_session', [name], [&'string'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. maxPlayers: int [br]
func create_game(maxPlayers: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('create_game', [maxPlayers], [&'u32'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. name: String [br]
func create_player(name: String, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('create_player', [name], [&'string'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. gameId: int [br]
func delete_game(gameId: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('delete_game', [gameId], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. identity: PackedByteArray [br]
func delete_player(identity: PackedByteArray, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('delete_player', [identity], [&'identity'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. id: int [br]
func hard_delete_message(id: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('hard_delete_message', [id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. id: int [br]
func join_chat_session(id: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('join_chat_session', [id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. gameId: int [br]
func join_game(gameId: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('join_game', [gameId], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. id: int [br]
func leave_chat_session(id: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('leave_chat_session', [id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. gameId: int [br]
func leave_game(gameId: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('leave_game', [gameId], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. gameId: int [br]
## 1. newPosition: TvsDbVector3 [br]
func move_player(gameId: int, newPosition: TvsDbVector3, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('move_player', [gameId, newPosition], [&'u64', &'TvsDbVector3'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. id: int [br]
func remove_chat_session_by_id(id: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('remove_chat_session_by_id', [id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. name: String [br]
func remove_chat_session_by_name(name: String, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('remove_chat_session_by_name', [name], [&'string'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. message: String [br]
## 1. chatSessionId: int [br]
func send_message(message: String, chatSessionId: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('send_message', [message, chatSessionId], [&'string', &'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. id: int [br]
func soft_delete_message(id: int, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('soft_delete_message', [id], [&'u64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK
