# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsModuleClient extends SpacetimeDBClient

const Types = preload('res://spacetime_bindings/schema/module_tvs_types.gd')

const DbVector3 = Types.DbVector3
const ChatSession = Types.ChatSession
const ChatSessionPlayer = Types.ChatSessionPlayer
const GamePlayer = Types.GamePlayer
const GameSession = Types.GameSession
const SessionState = Types.SessionState
const Message = Types.Message
const Player = Types.Player

var reducers: TvsModuleReducers
var db: TvsModuleDb

func _init() -> void:
	set_meta("module_name", "Tvs")
	name = "TvsModule"
	reducers = preload('res://spacetime_bindings/schema/module_tvs_reducers.gd').new(self)

func _init_db(p_local_db: LocalDatabase) -> void:
	db = preload('res://spacetime_bindings/schema/module_tvs_db.gd').new(p_local_db)
