# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const DbVector3 = preload('res://spacetime_bindings/schema/types/tvs_db_vector_3.gd')
const ChatSession = preload('res://spacetime_bindings/schema/types/tvs_chat_session.gd')
const ChatSessionPlayer = preload('res://spacetime_bindings/schema/types/tvs_chat_session_player.gd')
const GamePlayer = preload('res://spacetime_bindings/schema/types/tvs_game_player.gd')
const GameSession = preload('res://spacetime_bindings/schema/types/tvs_game_session.gd')
enum SessionState {
	Lobby,
	InProgress,
	Ended
}
const Message = preload('res://spacetime_bindings/schema/types/tvs_message.gd')
const Player = preload('res://spacetime_bindings/schema/types/tvs_player.gd')
