# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsModuleDb extends RefCounted

const table_names : Array[String] = ["chat_session", "chat_session_player", "game_player", "game_session", "message", "player"]

var chat_session: TvsChatSessionTable
var chat_session_player: TvsChatSessionPlayerTable
var game_player: TvsGamePlayerTable
var game_session: TvsGameSessionTable
var message: TvsMessageTable
var player: TvsPlayerTable

func _init(p_local_db: LocalDatabase) -> void:
	chat_session = preload('res://spacetime_bindings/schema/tables/tvs_chat_session_table.gd').new(p_local_db)
	chat_session_player = preload('res://spacetime_bindings/schema/tables/tvs_chat_session_player_table.gd').new(p_local_db)
	game_player = preload('res://spacetime_bindings/schema/tables/tvs_game_player_table.gd').new(p_local_db)
	game_session = preload('res://spacetime_bindings/schema/tables/tvs_game_session_table.gd').new(p_local_db)
	message = preload('res://spacetime_bindings/schema/tables/tvs_message_table.gd').new(p_local_db)
	player = preload('res://spacetime_bindings/schema/tables/tvs_player_table.gd').new(p_local_db)
