# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
extends Node
#SpacetimeDB Autoload

var Tvs: TvsModuleClient

func _init() -> void:
	Tvs = preload('res://spacetime_bindings/schema/module_tvs_client.gd').new()
	add_child(Tvs)
