// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AckPositionOverrideHandler(ReducerEventContext ctx, ulong overrideId);
        public event AckPositionOverrideHandler? OnAckPositionOverride;

        public void AckPositionOverride(ulong overrideId)
        {
            conn.InternalCallReducer(new Reducer.AckPositionOverride(overrideId));
        }

        public bool InvokeAckPositionOverride(ReducerEventContext ctx, Reducer.AckPositionOverride args)
        {
            if (OnAckPositionOverride == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAckPositionOverride(
                ctx,
                args.OverrideId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AckPositionOverride : Reducer, IReducerArgs
        {
            [DataMember(Name = "override_id")]
            public ulong OverrideId;

            public AckPositionOverride(ulong OverrideId)
            {
                this.OverrideId = OverrideId;
            }

            public AckPositionOverride()
            {
            }

            string IReducerArgs.ReducerName => "ack_position_override";
        }
    }
}
