// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinChatSessionHandler(ReducerEventContext ctx, ulong id);
        public event JoinChatSessionHandler? OnJoinChatSession;

        public void JoinChatSession(ulong id)
        {
            conn.InternalCallReducer(new Reducer.JoinChatSession(id));
        }

        public bool InvokeJoinChatSession(ReducerEventContext ctx, Reducer.JoinChatSession args)
        {
            if (OnJoinChatSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinChatSession(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinChatSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public JoinChatSession(ulong Id)
            {
                this.Id = Id;
            }

            public JoinChatSession()
            {
            }

            string IReducerArgs.ReducerName => "join_chat_session";
        }
    }
}
