// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SoftDeleteMessageHandler(ReducerEventContext ctx, ulong id);
        public event SoftDeleteMessageHandler? OnSoftDeleteMessage;

        public void SoftDeleteMessage(ulong id)
        {
            conn.InternalCallReducer(new Reducer.SoftDeleteMessage(id));
        }

        public bool InvokeSoftDeleteMessage(ReducerEventContext ctx, Reducer.SoftDeleteMessage args)
        {
            if (OnSoftDeleteMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSoftDeleteMessage(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SoftDeleteMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public SoftDeleteMessage(ulong Id)
            {
                this.Id = Id;
            }

            public SoftDeleteMessage()
            {
            }

            string IReducerArgs.ReducerName => "soft_delete_message";
        }
    }
}
