// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GamePlayer
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "player_identity")]
        public SpacetimeDB.Identity PlayerIdentity;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;

        public GamePlayer(
            ulong Id,
            ulong GameSessionId,
            SpacetimeDB.Identity PlayerIdentity,
            byte TeamSlot
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.PlayerIdentity = PlayerIdentity;
            this.TeamSlot = TeamSlot;
        }

        public GamePlayer()
        {
        }
    }
}
