// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.4 (commit 8b63d6398ae59c11ebb3af5935da75942ace472c).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	public sealed partial class RemoteReducers : RemoteBase
	{
		internal RemoteReducers(DbConnection conn) : base(conn) { }
		internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
	}

	public sealed partial class RemoteProcedures : RemoteBase
	{
		internal RemoteProcedures(DbConnection conn) : base(conn) { }
	}

	public sealed partial class RemoteTables : RemoteTablesBase
	{
		public RemoteTables(DbConnection conn)
		{
			AddTable(ChatSession = new(conn));
			AddTable(ChatSessionPlayer = new(conn));
			AddTable(Message = new(conn));
			AddTable(PositionOverride = new(conn));
			AddTable(AbilityCooldown = new(conn));
			AddTable(AbilityDef = new(conn));
			AddTable(ActiveEffect = new(conn));
			AddTable(ArchetypeDef = new(conn));
			AddTable(BattleLog = new(conn));
			AddTable(CapturePoint = new(conn));
			AddTable(Corpse = new(conn));
			AddTable(GamePlayer = new(conn));
			AddTable(GameSession = new(conn));
			AddTable(Loadout = new(conn));
			AddTable(Player = new(conn));
			AddTable(ResourcePool = new(conn));
			AddTable(SkillDef = new(conn));
			AddTable(Soldier = new(conn));
			AddTable(Squad = new(conn));
			AddTable(TerrainFeature = new(conn));
			AddTable(WeaponDef = new(conn));
		}
	}


		public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures> {
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
		}

		public sealed class EventContext : IEventContext, IRemoteDbContext
		{
			private readonly DbConnection conn;

			/// <summary>
			/// The event that caused this callback to run.
			/// </summary>
			public readonly Event<Reducer> Event;

			/// <summary>
			/// Access to tables in the client cache, which stores a read-only replica of the remote database state.
			///
			/// The returned <c>DbView</c> will have a method to access each table defined by the module.
			/// </summary>
			public RemoteTables Db => conn.Db;
			/// <summary>
			/// Access to reducers defined by the module.
			///
			/// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
			/// plus methods for adding and removing callbacks on each of those reducers.
			/// </summary>
			public RemoteReducers Reducers => conn.Reducers;
			/// <summary>
			/// Access to procedures defined by the module.
			///
			/// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
			/// with a callback for when the procedure completes and returns a value.
			/// </summary>
			public RemoteProcedures Procedures => conn.Procedures;
			/// <summary>
			/// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
			/// </summary>
			public bool IsActive => conn.IsActive;
			/// <summary>
			/// Close the connection.
			///
			/// Throws an error if the connection is already closed.
			/// </summary>
			public void Disconnect() {
				conn.Disconnect();
			}
			/// <summary>
			/// Start building a subscription.
			/// </summary>
			/// <returns>A builder-pattern constructor for subscribing to queries,
			/// causing matching rows to be replicated into the client cache.</returns>
			public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
			/// <summary>
			/// Get the <c>Identity</c> of this connection.
			///
			/// This method returns null if the connection was constructed anonymously
			/// and we have not yet received our newly-generated <c>Identity</c> from the host.
			/// </summary>
			public Identity? Identity => conn.Identity;
			/// <summary>
			/// Get this connection's <c>ConnectionId</c>.
			/// </summary>
			public ConnectionId ConnectionId => conn.ConnectionId;
			/// <summary>
			/// Register a callback to be called when a reducer with no handler returns an error.
			/// </summary>
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
				add => Reducers.InternalOnUnhandledReducerError += value;
				remove => Reducers.InternalOnUnhandledReducerError -= value;
			}

			internal EventContext(DbConnection conn, Event<Reducer> Event)
			{
				this.conn = conn;
				this.Event = Event;
			}
		}

		public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
		{
			private readonly DbConnection conn;
			/// <summary>
			/// The reducer event that caused this callback to run.
			/// </summary>
			public readonly ReducerEvent<Reducer> Event;

			/// <summary>
			/// Access to tables in the client cache, which stores a read-only replica of the remote database state.
			///
			/// The returned <c>DbView</c> will have a method to access each table defined by the module.
			/// </summary>
			public RemoteTables Db => conn.Db;
			/// <summary>
			/// Access to reducers defined by the module.
			///
			/// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
			/// plus methods for adding and removing callbacks on each of those reducers.
			/// </summary>
			public RemoteReducers Reducers => conn.Reducers;
			/// <summary>
			/// Access to procedures defined by the module.
			///
			/// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
			/// with a callback for when the procedure completes and returns a value.
			/// </summary>
			public RemoteProcedures Procedures => conn.Procedures;
			/// <summary>
			/// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
			/// </summary>
			public bool IsActive => conn.IsActive;
			/// <summary>
			/// Close the connection.
			///
			/// Throws an error if the connection is already closed.
			/// </summary>
			public void Disconnect() {
				conn.Disconnect();
			}
			/// <summary>
			/// Start building a subscription.
			/// </summary>
			/// <returns>A builder-pattern constructor for subscribing to queries,
			/// causing matching rows to be replicated into the client cache.</returns>
			public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
			/// <summary>
			/// Get the <c>Identity</c> of this connection.
			///
			/// This method returns null if the connection was constructed anonymously
			/// and we have not yet received our newly-generated <c>Identity</c> from the host.
			/// </summary>
			public Identity? Identity => conn.Identity;
			/// <summary>
			/// Get this connection's <c>ConnectionId</c>.
			/// </summary>
			public ConnectionId ConnectionId => conn.ConnectionId;
			/// <summary>
			/// Register a callback to be called when a reducer with no handler returns an error.
			/// </summary>
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
				add => Reducers.InternalOnUnhandledReducerError += value;
				remove => Reducers.InternalOnUnhandledReducerError -= value;
			}

			internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
			{
				this.conn = conn;
				Event = reducerEvent;
			}
		}

		public sealed class ErrorContext : IErrorContext, IRemoteDbContext
		{
			private readonly DbConnection conn;
			/// <summary>
			/// The <c>Exception</c> that caused this error callback to be run.
			/// </summary>
			public readonly Exception Event;
			Exception IErrorContext.Event {
				get {
					return Event;
				}
			}

			/// <summary>
			/// Access to tables in the client cache, which stores a read-only replica of the remote database state.
			///
			/// The returned <c>DbView</c> will have a method to access each table defined by the module.
			/// </summary>
			public RemoteTables Db => conn.Db;
			/// <summary>
			/// Access to reducers defined by the module.
			///
			/// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
			/// plus methods for adding and removing callbacks on each of those reducers.
			/// </summary>
			public RemoteReducers Reducers => conn.Reducers;
			/// <summary>
			/// Access to procedures defined by the module.
			///
			/// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
			/// with a callback for when the procedure completes and returns a value.
			/// </summary>
			public RemoteProcedures Procedures => conn.Procedures;
			/// <summary>
			/// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
			/// </summary>
			public bool IsActive => conn.IsActive;
			/// <summary>
			/// Close the connection.
			///
			/// Throws an error if the connection is already closed.
			/// </summary>
			public void Disconnect() {
				conn.Disconnect();
			}
			/// <summary>
			/// Start building a subscription.
			/// </summary>
			/// <returns>A builder-pattern constructor for subscribing to queries,
			/// causing matching rows to be replicated into the client cache.</returns>
			public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
			/// <summary>
			/// Get the <c>Identity</c> of this connection.
			///
			/// This method returns null if the connection was constructed anonymously
			/// and we have not yet received our newly-generated <c>Identity</c> from the host.
			/// </summary>
			public Identity? Identity => conn.Identity;
			/// <summary>
			/// Get this connection's <c>ConnectionId</c>.
			/// </summary>
			public ConnectionId ConnectionId => conn.ConnectionId;
			/// <summary>
			/// Register a callback to be called when a reducer with no handler returns an error.
			/// </summary>
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
				add => Reducers.InternalOnUnhandledReducerError += value;
				remove => Reducers.InternalOnUnhandledReducerError -= value;
			}

			internal ErrorContext(DbConnection conn, Exception error)
			{
				this.conn = conn;
				Event = error;
			}
		}

		public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
		{
			private readonly DbConnection conn;

			/// <summary>
			/// Access to tables in the client cache, which stores a read-only replica of the remote database state.
			///
			/// The returned <c>DbView</c> will have a method to access each table defined by the module.
			/// </summary>
			public RemoteTables Db => conn.Db;
			/// <summary>
			/// Access to reducers defined by the module.
			///
			/// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
			/// plus methods for adding and removing callbacks on each of those reducers.
			/// </summary>
			public RemoteReducers Reducers => conn.Reducers;
			/// <summary>
			/// Access to procedures defined by the module.
			///
			/// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
			/// with a callback for when the procedure completes and returns a value.
			/// </summary>
			public RemoteProcedures Procedures => conn.Procedures;
			/// <summary>
			/// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
			/// </summary>
			public bool IsActive => conn.IsActive;
			/// <summary>
			/// Close the connection.
			///
			/// Throws an error if the connection is already closed.
			/// </summary>
			public void Disconnect() {
				conn.Disconnect();
			}
			/// <summary>
			/// Start building a subscription.
			/// </summary>
			/// <returns>A builder-pattern constructor for subscribing to queries,
			/// causing matching rows to be replicated into the client cache.</returns>
			public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
			/// <summary>
			/// Get the <c>Identity</c> of this connection.
			///
			/// This method returns null if the connection was constructed anonymously
			/// and we have not yet received our newly-generated <c>Identity</c> from the host.
			/// </summary>
			public Identity? Identity => conn.Identity;
			/// <summary>
			/// Get this connection's <c>ConnectionId</c>.
			/// </summary>
			public ConnectionId ConnectionId => conn.ConnectionId;
			/// <summary>
			/// Register a callback to be called when a reducer with no handler returns an error.
			/// </summary>
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
				add => Reducers.InternalOnUnhandledReducerError += value;
				remove => Reducers.InternalOnUnhandledReducerError -= value;
			}

			internal SubscriptionEventContext(DbConnection conn)
			{
				this.conn = conn;
			}
		}

		public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
		{
			private readonly DbConnection conn;
			/// <summary>
			/// The procedure event that caused this callback to run.
			/// </summary>
			public readonly ProcedureEvent Event;

			/// <summary>
			/// Access to tables in the client cache, which stores a read-only replica of the remote database state.
			///
			/// The returned <c>DbView</c> will have a method to access each table defined by the module.
			/// </summary>
			public RemoteTables Db => conn.Db;
			/// <summary>
			/// Access to reducers defined by the module.
			///
			/// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
			/// plus methods for adding and removing callbacks on each of those reducers.
			/// </summary>
			public RemoteReducers Reducers => conn.Reducers;
			/// <summary>
			/// Access to procedures defined by the module.
			///
			/// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
			/// with a callback for when the procedure completes and returns a value.
			/// </summary>
			public RemoteProcedures Procedures => conn.Procedures;
			/// <summary>
			/// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
			/// </summary>
			public bool IsActive => conn.IsActive;
			/// <summary>
			/// Close the connection.
			///
			/// Throws an error if the connection is already closed.
			/// </summary>
			public void Disconnect() {
				conn.Disconnect();
			}
			/// <summary>
			/// Start building a subscription.
			/// </summary>
			/// <returns>A builder-pattern constructor for subscribing to queries,
			/// causing matching rows to be replicated into the client cache.</returns>
			public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
			/// <summary>
			/// Get the <c>Identity</c> of this connection.
			///
			/// This method returns null if the connection was constructed anonymously
			/// and we have not yet received our newly-generated <c>Identity</c> from the host.
			/// </summary>
			public Identity? Identity => conn.Identity;
			/// <summary>
			/// Get this connection's <c>ConnectionId</c>.
			/// </summary>
			public ConnectionId ConnectionId => conn.ConnectionId;
			/// <summary>
			/// Register a callback to be called when a reducer with no handler returns an error.
			/// </summary>
			public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
				add => Reducers.InternalOnUnhandledReducerError += value;
				remove => Reducers.InternalOnUnhandledReducerError -= value;
			}

			internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
			{
				this.conn = conn;
				this.Event = Event;
			}
		}

		/// <summary>
		/// Builder-pattern constructor for subscription queries.
		/// </summary>
		public sealed class SubscriptionBuilder
		{
			private readonly IDbConnection conn;

			private event Action<SubscriptionEventContext>? Applied;
			private event Action<ErrorContext, Exception>? Error;

			/// <summary>
			/// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
			/// </summary>
			public SubscriptionBuilder(IDbConnection conn)
			{
				this.conn = conn;
			}

			/// <summary>
			/// Register a callback to run when the subscription is applied.
			/// </summary>
			public SubscriptionBuilder OnApplied(
				Action<SubscriptionEventContext> callback
			)
			{
				Applied += callback;
				return this;
			}

			/// <summary>
			/// Register a callback to run when the subscription fails.
			///
			/// Note that this callback may run either when attempting to apply the subscription,
			/// in which case <c>Self::on_applied</c> will never run,
			/// or later during the subscription's lifetime if the module's interface changes,
			/// in which case <c>Self::on_applied</c> may have already run.
			/// </summary>
			public SubscriptionBuilder OnError(
				Action<ErrorContext, Exception> callback
			)
			{
				Error += callback;
				return this;
			}
		
			/// <summary>
			/// Add a typed query to this subscription.
			///
			/// This is the entry point for building subscriptions without writing SQL by hand.
			/// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
			/// </summary>
			public TypedSubscriptionBuilder AddQuery<TRow>(
				Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
			)
			{
				var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
				return typed.AddQuery(build);
			}

			/// <summary>
			/// Subscribe to the following SQL queries.
			///
			/// This method returns immediately, with the data not yet added to the DbConnection.
			/// The provided callbacks will be invoked once the data is returned from the remote server.
			/// Data from all the provided queries will be returned at the same time.
			///
			/// See the SpacetimeDB SQL docs for more information on SQL syntax:
			/// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
			/// </summary>
			public SubscriptionHandle Subscribe(
				string[] querySqls
			) => new(conn, Applied, Error, querySqls);

			/// <summary>
			/// Subscribe to all rows from all tables.
			///
			/// This method is intended as a convenience
			/// for applications where client-side memory use and network bandwidth are not concerns.
			/// Applications where these resources are a constraint
			/// should register more precise queries via <c>Self.Subscribe</c>
			/// in order to replicate only the subset of data which the client needs to function.
			///
			/// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
			/// A connection may either <c>Self.Subscribe</c> to particular queries,
			/// or <c>Self.SubscribeToAllTables</c>, but not both.
			/// Attempting to call <c>Self.Subscribe</c>
			/// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
			/// or vice versa, may misbehave in any number of ways,
			/// including dropping subscriptions, corrupting the client cache, or panicking.
			/// </summary>
			public SubscriptionHandle SubscribeToAllTables() =>
				new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
		}

		public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext> {
			/// <summary>
			/// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
			/// </summary>
			public SubscriptionHandle(
				IDbConnection conn,
				Action<SubscriptionEventContext>? onApplied,
				Action<ErrorContext, Exception>? onError,
				string[] querySqls
			) : base(conn, onApplied, onError, querySqls)
			{ }
		}

	public sealed class QueryBuilder
	{
		public From From { get; } = new();

		internal static string[] AllTablesSqlQueries() => new string[]
		{
			new QueryBuilder().From.ChatSession().ToSql(),
			new QueryBuilder().From.ChatSessionPlayer().ToSql(),
			new QueryBuilder().From.Message().ToSql(),
			new QueryBuilder().From.PositionOverride().ToSql(),
			new QueryBuilder().From.AbilityCooldown().ToSql(),
			new QueryBuilder().From.AbilityDef().ToSql(),
			new QueryBuilder().From.ActiveEffect().ToSql(),
			new QueryBuilder().From.ArchetypeDef().ToSql(),
			new QueryBuilder().From.BattleLog().ToSql(),
			new QueryBuilder().From.CapturePoint().ToSql(),
			new QueryBuilder().From.Corpse().ToSql(),
			new QueryBuilder().From.GamePlayer().ToSql(),
			new QueryBuilder().From.GameSession().ToSql(),
			new QueryBuilder().From.Loadout().ToSql(),
			new QueryBuilder().From.Player().ToSql(),
			new QueryBuilder().From.ResourcePool().ToSql(),
			new QueryBuilder().From.SkillDef().ToSql(),
			new QueryBuilder().From.Soldier().ToSql(),
			new QueryBuilder().From.Squad().ToSql(),
			new QueryBuilder().From.TerrainFeature().ToSql(),
			new QueryBuilder().From.WeaponDef().ToSql(),
		}
		;
	}

	public sealed class From
	{
		public global::SpacetimeDB.Table<ChatSession, ChatSessionCols, ChatSessionIxCols> ChatSession() => new("chat_session", new ChatSessionCols("chat_session"), new ChatSessionIxCols("chat_session"));
		public global::SpacetimeDB.Table<ChatSessionPlayer, ChatSessionPlayerCols, ChatSessionPlayerIxCols> ChatSessionPlayer() => new("chat_session_player", new ChatSessionPlayerCols("chat_session_player"), new ChatSessionPlayerIxCols("chat_session_player"));
		public global::SpacetimeDB.Table<Message, MessageCols, MessageIxCols> Message() => new("message", new MessageCols("message"), new MessageIxCols("message"));
		public global::SpacetimeDB.Table<PositionOverride, PositionOverrideCols, PositionOverrideIxCols> PositionOverride() => new("position_override", new PositionOverrideCols("position_override"), new PositionOverrideIxCols("position_override"));
		public global::SpacetimeDB.Table<AbilityCooldown, AbilityCooldownCols, AbilityCooldownIxCols> AbilityCooldown() => new("ability_cooldown", new AbilityCooldownCols("ability_cooldown"), new AbilityCooldownIxCols("ability_cooldown"));
		public global::SpacetimeDB.Table<AbilityDef, AbilityDefCols, AbilityDefIxCols> AbilityDef() => new("ability_def", new AbilityDefCols("ability_def"), new AbilityDefIxCols("ability_def"));
		public global::SpacetimeDB.Table<ActiveEffect, ActiveEffectCols, ActiveEffectIxCols> ActiveEffect() => new("active_effect", new ActiveEffectCols("active_effect"), new ActiveEffectIxCols("active_effect"));
		public global::SpacetimeDB.Table<ArchetypeDef, ArchetypeDefCols, ArchetypeDefIxCols> ArchetypeDef() => new("archetype_def", new ArchetypeDefCols("archetype_def"), new ArchetypeDefIxCols("archetype_def"));
		public global::SpacetimeDB.Table<BattleLogEntry, BattleLogCols, BattleLogIxCols> BattleLog() => new("battle_log", new BattleLogCols("battle_log"), new BattleLogIxCols("battle_log"));
		public global::SpacetimeDB.Table<CapturePoint, CapturePointCols, CapturePointIxCols> CapturePoint() => new("capture_point", new CapturePointCols("capture_point"), new CapturePointIxCols("capture_point"));
		public global::SpacetimeDB.Table<Corpse, CorpseCols, CorpseIxCols> Corpse() => new("corpse", new CorpseCols("corpse"), new CorpseIxCols("corpse"));
		public global::SpacetimeDB.Table<GamePlayer, GamePlayerCols, GamePlayerIxCols> GamePlayer() => new("game_player", new GamePlayerCols("game_player"), new GamePlayerIxCols("game_player"));
		public global::SpacetimeDB.Table<GameSession, GameSessionCols, GameSessionIxCols> GameSession() => new("game_session", new GameSessionCols("game_session"), new GameSessionIxCols("game_session"));
		public global::SpacetimeDB.Table<Loadout, LoadoutCols, LoadoutIxCols> Loadout() => new("loadout", new LoadoutCols("loadout"), new LoadoutIxCols("loadout"));
		public global::SpacetimeDB.Table<Player, PlayerCols, PlayerIxCols> Player() => new("player", new PlayerCols("player"), new PlayerIxCols("player"));
		public global::SpacetimeDB.Table<ResourcePool, ResourcePoolCols, ResourcePoolIxCols> ResourcePool() => new("resource_pool", new ResourcePoolCols("resource_pool"), new ResourcePoolIxCols("resource_pool"));
		public global::SpacetimeDB.Table<SkillDef, SkillDefCols, SkillDefIxCols> SkillDef() => new("skill_def", new SkillDefCols("skill_def"), new SkillDefIxCols("skill_def"));
		public global::SpacetimeDB.Table<Soldier, SoldierCols, SoldierIxCols> Soldier() => new("soldier", new SoldierCols("soldier"), new SoldierIxCols("soldier"));
		public global::SpacetimeDB.Table<Squad, SquadCols, SquadIxCols> Squad() => new("squad", new SquadCols("squad"), new SquadIxCols("squad"));
		public global::SpacetimeDB.Table<TerrainFeature, TerrainFeatureCols, TerrainFeatureIxCols> TerrainFeature() => new("terrain_feature", new TerrainFeatureCols("terrain_feature"), new TerrainFeatureIxCols("terrain_feature"));
		public global::SpacetimeDB.Table<WeaponDef, WeaponDefCols, WeaponDefIxCols> WeaponDef() => new("weapon_def", new WeaponDefCols("weapon_def"), new WeaponDefIxCols("weapon_def"));
	}

	public sealed class TypedSubscriptionBuilder
	{
		private readonly IDbConnection conn;
		private Action<SubscriptionEventContext>? Applied;
		private Action<ErrorContext, Exception>? Error;
		private readonly List<string> querySqls = new();

		internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
		{
			this.conn = conn;
			Applied = applied;
			Error = error;
		}

		public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
		{
			Applied += callback;
			return this;
		}

		public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
		{
			Error += callback;
			return this;
		}

		public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
		{
			var qb = new QueryBuilder();
			querySqls.Add(build(qb).ToSql());
			return this;
		}

		public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
	}

	public abstract partial class Reducer
	{
		private Reducer() { }
	}

	public abstract partial class Procedure
	{
		private Procedure() { }
	}

	public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
	{
		public override RemoteTables Db { get; }
		public readonly RemoteReducers Reducers;
		public readonly RemoteProcedures Procedures;

		public DbConnection()
		{
			Db = new(this);
			Reducers = new(this);
			Procedures = new(this);
		}

		protected override IEventContext ToEventContext(Event<Reducer> Event) =>
		new EventContext(this, Event);

		protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
		new ReducerEventContext(this, reducerEvent);

		protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
		new SubscriptionEventContext(this);

		protected override IErrorContext ToErrorContext(Exception exception) =>
		new ErrorContext(this, exception);

		protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
		new ProcedureEventContext(this, procedureEvent);

		protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
		{
			var eventContext = (ReducerEventContext)context;
			return reducer switch {
				Reducer.AckPositionOverride args => Reducers.InvokeAckPositionOverride(eventContext, args),
				Reducer.ClearData args => Reducers.InvokeClearData(eventContext, args),
				Reducer.CreateChatSession args => Reducers.InvokeCreateChatSession(eventContext, args),
				Reducer.CreateGame args => Reducers.InvokeCreateGame(eventContext, args),
				Reducer.CreateGameAndJoin args => Reducers.InvokeCreateGameAndJoin(eventContext, args),
				Reducer.CreatePlayer args => Reducers.InvokeCreatePlayer(eventContext, args),
				Reducer.DeleteGame args => Reducers.InvokeDeleteGame(eventContext, args),
				Reducer.DeletePlayer args => Reducers.InvokeDeletePlayer(eventContext, args),
				Reducer.DeselectPlayer args => Reducers.InvokeDeselectPlayer(eventContext, args),
				Reducer.EndGame args => Reducers.InvokeEndGame(eventContext, args),
				Reducer.HardDeleteMessage args => Reducers.InvokeHardDeleteMessage(eventContext, args),
				Reducer.JoinChatSession args => Reducers.InvokeJoinChatSession(eventContext, args),
				Reducer.JoinGame args => Reducers.InvokeJoinGame(eventContext, args),
				Reducer.KickPlayerFromGame args => Reducers.InvokeKickPlayerFromGame(eventContext, args),
				Reducer.LeaveChatSession args => Reducers.InvokeLeaveChatSession(eventContext, args),
				Reducer.LeaveGame args => Reducers.InvokeLeaveGame(eventContext, args),
				Reducer.MovePlayer args => Reducers.InvokeMovePlayer(eventContext, args),
				Reducer.RemoveChatSessionById args => Reducers.InvokeRemoveChatSessionById(eventContext, args),
				Reducer.RemoveChatSessionByName args => Reducers.InvokeRemoveChatSessionByName(eventContext, args),
				Reducer.Respawn args => Reducers.InvokeRespawn(eventContext, args),
				Reducer.SelectPlayer args => Reducers.InvokeSelectPlayer(eventContext, args),
				Reducer.SendMessage args => Reducers.InvokeSendMessage(eventContext, args),
				Reducer.SetLoadout args => Reducers.InvokeSetLoadout(eventContext, args),
				Reducer.SetTarget args => Reducers.InvokeSetTarget(eventContext, args),
				Reducer.SetTeam args => Reducers.InvokeSetTeam(eventContext, args),
				Reducer.SoftDeleteMessage args => Reducers.InvokeSoftDeleteMessage(eventContext, args),
				Reducer.SplitOwnedSquads args => Reducers.InvokeSplitOwnedSquads(eventContext, args),
				Reducer.StartGame args => Reducers.InvokeStartGame(eventContext, args),
				Reducer.TeleportPlayer args => Reducers.InvokeTeleportPlayer(eventContext, args),
				Reducer.UseAbility args => Reducers.InvokeUseAbility(eventContext, args),
				_ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
			};
		}

		public SubscriptionBuilder SubscriptionBuilder() => new(this);
		public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
		{
			add => Reducers.InternalOnUnhandledReducerError += value;
			remove => Reducers.InternalOnUnhandledReducerError -= value;
		}
	}
}
