// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndGameHandler(ReducerEventContext ctx, ulong gameId);
        public event EndGameHandler? OnEndGame;

        public void EndGame(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.EndGame(gameId));
        }

        public bool InvokeEndGame(ReducerEventContext ctx, Reducer.EndGame args)
        {
            if (OnEndGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEndGame(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public EndGame(ulong GameId)
            {
                this.GameId = GameId;
            }

            public EndGame()
            {
            }

            string IReducerArgs.ReducerName => "end_game";
        }
    }
}
