// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveChatSessionHandler(ReducerEventContext ctx, ulong id);
        public event LeaveChatSessionHandler? OnLeaveChatSession;

        public void LeaveChatSession(ulong id)
        {
            conn.InternalCallReducer(new Reducer.LeaveChatSession(id));
        }

        public bool InvokeLeaveChatSession(ReducerEventContext ctx, Reducer.LeaveChatSession args)
        {
            if (OnLeaveChatSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveChatSession(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveChatSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public LeaveChatSession(ulong Id)
            {
                this.Id = Id;
            }

            public LeaveChatSession()
            {
            }

            string IReducerArgs.ReducerName => "leave_chat_session";
        }
    }
}
