// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveChatSessionByNameHandler(ReducerEventContext ctx, string name);
        public event RemoveChatSessionByNameHandler? OnRemoveChatSessionByName;

        public void RemoveChatSessionByName(string name)
        {
            conn.InternalCallReducer(new Reducer.RemoveChatSessionByName(name));
        }

        public bool InvokeRemoveChatSessionByName(ReducerEventContext ctx, Reducer.RemoveChatSessionByName args)
        {
            if (OnRemoveChatSessionByName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveChatSessionByName(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveChatSessionByName : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public RemoveChatSessionByName(string Name)
            {
                this.Name = Name;
            }

            public RemoveChatSessionByName()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "remove_chat_session_by_name";
        }
    }
}
