// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveChatSessionByIdHandler(ReducerEventContext ctx, ulong id);
        public event RemoveChatSessionByIdHandler? OnRemoveChatSessionById;

        public void RemoveChatSessionById(ulong id)
        {
            conn.InternalCallReducer(new Reducer.RemoveChatSessionById(id));
        }

        public bool InvokeRemoveChatSessionById(ReducerEventContext ctx, Reducer.RemoveChatSessionById args)
        {
            if (OnRemoveChatSessionById == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveChatSessionById(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveChatSessionById : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ulong Id;

            public RemoveChatSessionById(ulong Id)
            {
                this.Id = Id;
            }

            public RemoveChatSessionById()
            {
            }

            string IReducerArgs.ReducerName => "remove_chat_session_by_id";
        }
    }
}
