// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RespawnHandler(ReducerEventContext ctx, ulong gameId);
        public event RespawnHandler? OnRespawn;

        public void Respawn(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.Respawn(gameId));
        }

        public bool InvokeRespawn(ReducerEventContext ctx, Reducer.Respawn args)
        {
            if (OnRespawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRespawn(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Respawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public Respawn(ulong GameId)
            {
                this.GameId = GameId;
            }

            public Respawn()
            {
            }

            string IReducerArgs.ReducerName => "respawn";
        }
    }
}
