// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendMessageHandler(ReducerEventContext ctx, string message, ulong chatSessionId);
        public event SendMessageHandler? OnSendMessage;

        public void SendMessage(string message, ulong chatSessionId)
        {
            conn.InternalCallReducer(new Reducer.SendMessage(message, chatSessionId));
        }

        public bool InvokeSendMessage(ReducerEventContext ctx, Reducer.SendMessage args)
        {
            if (OnSendMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendMessage(
                ctx,
                args.Message,
                args.ChatSessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "message")]
            public string Message;
            [DataMember(Name = "chat_session_id")]
            public ulong ChatSessionId;

            public SendMessage(
                string Message,
                ulong ChatSessionId
            )
            {
                this.Message = Message;
                this.ChatSessionId = ChatSessionId;
            }

            public SendMessage()
            {
                this.Message = "";
            }

            string IReducerArgs.ReducerName => "send_message";
        }
    }
}
