// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetTeamHandler(ReducerEventContext ctx, ulong gameId, byte teamSlot);
        public event SetTeamHandler? OnSetTeam;

        public void SetTeam(ulong gameId, byte teamSlot)
        {
            conn.InternalCallReducer(new Reducer.SetTeam(gameId, teamSlot));
        }

        public bool InvokeSetTeam(ReducerEventContext ctx, Reducer.SetTeam args)
        {
            if (OnSetTeam == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetTeam(
                ctx,
                args.GameId,
                args.TeamSlot
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetTeam : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "team_slot")]
            public byte TeamSlot;

            public SetTeam(
                ulong GameId,
                byte TeamSlot
            )
            {
                this.GameId = GameId;
                this.TeamSlot = TeamSlot;
            }

            public SetTeam()
            {
            }

            string IReducerArgs.ReducerName => "set_team";
        }
    }
}
