// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetTargetHandler(ReducerEventContext ctx, ulong gameId, ulong? targetEntityId);
        public event SetTargetHandler? OnSetTarget;

        public void SetTarget(ulong gameId, ulong? targetEntityId)
        {
            conn.InternalCallReducer(new Reducer.SetTarget(gameId, targetEntityId));
        }

        public bool InvokeSetTarget(ReducerEventContext ctx, Reducer.SetTarget args)
        {
            if (OnSetTarget == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetTarget(
                ctx,
                args.GameId,
                args.TargetEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetTarget : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "target_entity_id")]
            public ulong? TargetEntityId;

            public SetTarget(
                ulong GameId,
                ulong? TargetEntityId
            )
            {
                this.GameId = GameId;
                this.TargetEntityId = TargetEntityId;
            }

            public SetTarget()
            {
            }

            string IReducerArgs.ReducerName => "set_target";
        }
    }
}
