// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SplitOwnedSquadsHandler(ReducerEventContext ctx, ulong gameId);
        public event SplitOwnedSquadsHandler? OnSplitOwnedSquads;

        public void SplitOwnedSquads(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.SplitOwnedSquads(gameId));
        }

        public bool InvokeSplitOwnedSquads(ReducerEventContext ctx, Reducer.SplitOwnedSquads args)
        {
            if (OnSplitOwnedSquads == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSplitOwnedSquads(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SplitOwnedSquads : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public SplitOwnedSquads(ulong GameId)
            {
                this.GameId = GameId;
            }

            public SplitOwnedSquads()
            {
            }

            string IReducerArgs.ReducerName => "split_owned_squads";
        }
    }
}
