// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartResupplyHandler(ReducerEventContext ctx, ulong gameId);
        public event StartResupplyHandler? OnStartResupply;

        public void StartResupply(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.StartResupply(gameId));
        }

        public bool InvokeStartResupply(ReducerEventContext ctx, Reducer.StartResupply args)
        {
            if (OnStartResupply == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartResupply(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartResupply : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public StartResupply(ulong GameId)
            {
                this.GameId = GameId;
            }

            public StartResupply()
            {
            }

            string IReducerArgs.ReducerName => "start_resupply";
        }
    }
}
