// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TeleportPlayerHandler(ReducerEventContext ctx, ulong gameSessionId, string playerName, SpacetimeDB.Types.DbVector3 position);
        public event TeleportPlayerHandler? OnTeleportPlayer;

        public void TeleportPlayer(ulong gameSessionId, string playerName, SpacetimeDB.Types.DbVector3 position)
        {
            conn.InternalCallReducer(new Reducer.TeleportPlayer(gameSessionId, playerName, position));
        }

        public bool InvokeTeleportPlayer(ReducerEventContext ctx, Reducer.TeleportPlayer args)
        {
            if (OnTeleportPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTeleportPlayer(
                ctx,
                args.GameSessionId,
                args.PlayerName,
                args.Position
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TeleportPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_session_id")]
            public ulong GameSessionId;
            [DataMember(Name = "player_name")]
            public string PlayerName;
            [DataMember(Name = "position")]
            public DbVector3 Position;

            public TeleportPlayer(
                ulong GameSessionId,
                string PlayerName,
                DbVector3 Position
            )
            {
                this.GameSessionId = GameSessionId;
                this.PlayerName = PlayerName;
                this.Position = Position;
            }

            public TeleportPlayer()
            {
                this.PlayerName = "";
                this.Position = new();
            }

            string IReducerArgs.ReducerName => "teleport_player";
        }
    }
}
