// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityCooldown
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_player_id")]
        public ulong GamePlayerId;
        [DataMember(Name = "ability_id")]
        public ulong AbilityId;
        [DataMember(Name = "ready_at")]
        public SpacetimeDB.Timestamp ReadyAt;

        public AbilityCooldown(
            ulong Id,
            ulong GamePlayerId,
            ulong AbilityId,
            SpacetimeDB.Timestamp ReadyAt
        )
        {
            this.Id = Id;
            this.GamePlayerId = GamePlayerId;
            this.AbilityId = AbilityId;
            this.ReadyAt = ReadyAt;
        }

        public AbilityCooldown()
        {
        }
    }
}
