// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityMod
    {
        [DataMember(Name = "type")]
        public ModType Type;
        [DataMember(Name = "value")]
        public float Value;

        public AbilityMod(
            ModType Type,
            float Value
        )
        {
            this.Type = Type;
            this.Value = Value;
        }

        public AbilityMod()
        {
        }
    }
}
