// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActiveEffect
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_player_id")]
        public ulong GamePlayerId;
        [DataMember(Name = "caster_game_player_id")]
        public ulong CasterGamePlayerId;
        [DataMember(Name = "source_ability_id")]
        public ulong SourceAbilityId;
        [DataMember(Name = "mods")]
        public System.Collections.Generic.List<AbilityMod> Mods;
        [DataMember(Name = "affected_ability_ids")]
        public System.Collections.Generic.List<ulong> AffectedAbilityIds;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp ExpiresAt;

        public ActiveEffect(
            ulong Id,
            ulong GamePlayerId,
            ulong CasterGamePlayerId,
            ulong SourceAbilityId,
            System.Collections.Generic.List<AbilityMod> Mods,
            System.Collections.Generic.List<ulong> AffectedAbilityIds,
            SpacetimeDB.Timestamp ExpiresAt
        )
        {
            this.Id = Id;
            this.GamePlayerId = GamePlayerId;
            this.CasterGamePlayerId = CasterGamePlayerId;
            this.SourceAbilityId = SourceAbilityId;
            this.Mods = Mods;
            this.AffectedAbilityIds = AffectedAbilityIds;
            this.ExpiresAt = ExpiresAt;
        }

        public ActiveEffect()
        {
            this.Mods = new();
            this.AffectedAbilityIds = new();
        }
    }
}
