// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ArchetypeDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "kind")]
        public ArchetypeKind Kind;
        [DataMember(Name = "bonus_health")]
        public int BonusHealth;
        [DataMember(Name = "bonus_armor")]
        public int BonusArmor;
        [DataMember(Name = "innate_ability_ids")]
        public System.Collections.Generic.List<ulong> InnateAbilityIds;

        public ArchetypeDef(
            ulong Id,
            string Name,
            string Description,
            ArchetypeKind Kind,
            int BonusHealth,
            int BonusArmor,
            System.Collections.Generic.List<ulong> InnateAbilityIds
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Kind = Kind;
            this.BonusHealth = BonusHealth;
            this.BonusArmor = BonusArmor;
            this.InnateAbilityIds = InnateAbilityIds;
        }

        public ArchetypeDef()
        {
            this.Name = "";
            this.Description = "";
            this.InnateAbilityIds = new();
        }
    }
}
