// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BattleLogEntry
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "occurred_at")]
        public SpacetimeDB.Timestamp OccurredAt;
        [DataMember(Name = "actor_game_player_id")]
        public ulong ActorGamePlayerId;
        [DataMember(Name = "ability_id")]
        public ulong AbilityId;
        [DataMember(Name = "from_weapon")]
        public bool FromWeapon;
        [DataMember(Name = "target_game_player_ids")]
        public System.Collections.Generic.List<ulong> TargetGamePlayerIds;
        [DataMember(Name = "resolved_power")]
        public int ResolvedPower;

        public BattleLogEntry(
            ulong Id,
            ulong GameSessionId,
            SpacetimeDB.Timestamp OccurredAt,
            ulong ActorGamePlayerId,
            ulong AbilityId,
            bool FromWeapon,
            System.Collections.Generic.List<ulong> TargetGamePlayerIds,
            int ResolvedPower
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.OccurredAt = OccurredAt;
            this.ActorGamePlayerId = ActorGamePlayerId;
            this.AbilityId = AbilityId;
            this.FromWeapon = FromWeapon;
            this.TargetGamePlayerIds = TargetGamePlayerIds;
            this.ResolvedPower = ResolvedPower;
        }

        public BattleLogEntry()
        {
            this.TargetGamePlayerIds = new();
        }
    }
}
