// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CapturePoint
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "owning_team")]
        public byte OwningTeam;
        [DataMember(Name = "influence_team_1")]
        public int InfluenceTeam1;
        [DataMember(Name = "influence_team_2")]
        public int InfluenceTeam2;
        [DataMember(Name = "max_influence")]
        public int MaxInfluence;

        public CapturePoint(
            ulong Id,
            ulong GameSessionId,
            float PosX,
            float PosZ,
            float Radius,
            byte OwningTeam,
            int InfluenceTeam1,
            int InfluenceTeam2,
            int MaxInfluence
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.PosX = PosX;
            this.PosZ = PosZ;
            this.Radius = Radius;
            this.OwningTeam = OwningTeam;
            this.InfluenceTeam1 = InfluenceTeam1;
            this.InfluenceTeam2 = InfluenceTeam2;
            this.MaxInfluence = MaxInfluence;
        }

        public CapturePoint()
        {
        }
    }
}
