// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatSession
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "time_created")]
        public SpacetimeDB.Timestamp TimeCreated;
        [DataMember(Name = "owner_player_id")]
        public ulong OwnerPlayerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "active")]
        public bool Active;

        public ChatSession(
            ulong Id,
            SpacetimeDB.Timestamp TimeCreated,
            ulong OwnerPlayerId,
            string Name,
            bool Active
        )
        {
            this.Id = Id;
            this.TimeCreated = TimeCreated;
            this.OwnerPlayerId = OwnerPlayerId;
            this.Name = Name;
            this.Active = Active;
        }

        public ChatSession()
        {
            this.Name = "";
        }
    }
}
