// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatSessionPlayer
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "session_id")]
        public ulong SessionId;

        public ChatSessionPlayer(
            ulong Id,
            ulong PlayerId,
            ulong SessionId
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.SessionId = SessionId;
        }

        public ChatSessionPlayer()
        {
        }
    }
}
