// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Corpse
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "game_player_id")]
        public ulong? GamePlayerId;
        [DataMember(Name = "soldier_id")]
        public ulong? SoldierId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation_y")]
        public float RotationY;

        public Corpse(
            ulong Id,
            ulong GameSessionId,
            ulong? GamePlayerId,
            ulong? SoldierId,
            ulong PlayerId,
            DbVector3 Position,
            float RotationY
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.GamePlayerId = GamePlayerId;
            this.SoldierId = SoldierId;
            this.PlayerId = PlayerId;
            this.Position = Position;
            this.RotationY = RotationY;
        }

        public Corpse()
        {
            this.Position = new();
        }
    }
}
