// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "type")]
        public EntityType Type;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation_y")]
        public float RotationY;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;

        public Entity(
            ulong EntityId,
            ulong GameSessionId,
            EntityType Type,
            DbVector3 Position,
            float RotationY,
            byte TeamSlot
        )
        {
            this.EntityId = EntityId;
            this.GameSessionId = GameSessionId;
            this.Type = Type;
            this.Position = Position;
            this.RotationY = RotationY;
            this.TeamSlot = TeamSlot;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
