// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GamePlayer
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;
        [DataMember(Name = "active")]
        public bool Active;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation_y")]
        public float RotationY;
        [DataMember(Name = "target_game_player_id")]
        public ulong? TargetGamePlayerId;

        public GamePlayer(
            ulong Id,
            ulong GameSessionId,
            ulong PlayerId,
            byte TeamSlot,
            bool Active,
            DbVector3 Position,
            float RotationY,
            ulong? TargetGamePlayerId
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.PlayerId = PlayerId;
            this.TeamSlot = TeamSlot;
            this.Active = Active;
            this.Position = Position;
            this.RotationY = RotationY;
            this.TargetGamePlayerId = TargetGamePlayerId;
        }

        public GamePlayer()
        {
            this.Position = new();
        }
    }
}
