// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GamePlayer
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "active")]
        public bool Active;
        [DataMember(Name = "target_entity_id")]
        public ulong? TargetEntityId;

        public GamePlayer(
            ulong EntityId,
            ulong PlayerId,
            bool Active,
            ulong? TargetEntityId
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Active = Active;
            this.TargetEntityId = TargetEntityId;
        }

        public GamePlayer()
        {
        }
    }
}
