// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Loadout
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "archetype_def_id")]
        public ulong ArchetypeDefId;
        [DataMember(Name = "weapon_def_id")]
        public ulong WeaponDefId;
        [DataMember(Name = "skill_def_id")]
        public ulong SkillDefId;

        public Loadout(
            ulong Id,
            ulong GameSessionId,
            ulong PlayerId,
            ulong ArchetypeDefId,
            ulong WeaponDefId,
            ulong SkillDefId
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.PlayerId = PlayerId;
            this.ArchetypeDefId = ArchetypeDefId;
            this.WeaponDefId = WeaponDefId;
            this.SkillDefId = SkillDefId;
        }

        public Loadout()
        {
        }
    }
}
