// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MapTerrainDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "map_def_id")]
        public ulong MapDefId;
        [DataMember(Name = "terrain_type")]
        public TerrainType TerrainType;
        [DataMember(Name = "position_x")]
        public float PositionX;
        [DataMember(Name = "position_y")]
        public float PositionY;
        [DataMember(Name = "position_z")]
        public float PositionZ;
        [DataMember(Name = "rotation_y")]
        public float RotationY;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;
        [DataMember(Name = "size_x")]
        public float SizeX;
        [DataMember(Name = "size_y")]
        public float SizeY;
        [DataMember(Name = "size_z")]
        public float SizeZ;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "armor")]
        public int Armor;
        [DataMember(Name = "has_outpost_regen")]
        public bool HasOutpostRegen;

        public MapTerrainDef(
            ulong Id,
            ulong MapDefId,
            TerrainType TerrainType,
            float PositionX,
            float PositionY,
            float PositionZ,
            float RotationY,
            byte TeamSlot,
            float SizeX,
            float SizeY,
            float SizeZ,
            int MaxHealth,
            int Armor,
            bool HasOutpostRegen
        )
        {
            this.Id = Id;
            this.MapDefId = MapDefId;
            this.TerrainType = TerrainType;
            this.PositionX = PositionX;
            this.PositionY = PositionY;
            this.PositionZ = PositionZ;
            this.RotationY = RotationY;
            this.TeamSlot = TeamSlot;
            this.SizeX = SizeX;
            this.SizeY = SizeY;
            this.SizeZ = SizeZ;
            this.MaxHealth = MaxHealth;
            this.Armor = Armor;
            this.HasOutpostRegen = HasOutpostRegen;
        }

        public MapTerrainDef()
        {
        }
    }
}
