// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "body")]
        public string Body;
        [DataMember(Name = "session_id")]
        public ulong SessionId;
        [DataMember(Name = "sender_player_id")]
        public ulong SenderPlayerId;
        [DataMember(Name = "deleted")]
        public bool Deleted;
        [DataMember(Name = "time_sent")]
        public SpacetimeDB.Timestamp TimeSent;

        public Message(
            ulong Id,
            string Body,
            ulong SessionId,
            ulong SenderPlayerId,
            bool Deleted,
            SpacetimeDB.Timestamp TimeSent
        )
        {
            this.Id = Id;
            this.Body = Body;
            this.SessionId = SessionId;
            this.SenderPlayerId = SenderPlayerId;
            this.Deleted = Deleted;
            this.TimeSent = TimeSent;
        }

        public Message()
        {
            this.Body = "";
        }
    }
}
