// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner_identity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "controller_identity")]
        public SpacetimeDB.Identity? ControllerIdentity;

        public Player(
            ulong Id,
            SpacetimeDB.Identity OwnerIdentity,
            string Name,
            bool Online,
            SpacetimeDB.Identity? ControllerIdentity
        )
        {
            this.Id = Id;
            this.OwnerIdentity = OwnerIdentity;
            this.Name = Name;
            this.Online = Online;
            this.ControllerIdentity = ControllerIdentity;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
