// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Projectile
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "caster_entity_id")]
        public ulong CasterEntityId;
        [DataMember(Name = "ability_id")]
        public ulong AbilityId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "direction_x")]
        public float DirectionX;
        [DataMember(Name = "direction_y")]
        public float DirectionY;
        [DataMember(Name = "direction_z")]
        public float DirectionZ;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "max_range")]
        public float MaxRange;
        [DataMember(Name = "distance_traveled")]
        public float DistanceTraveled;
        [DataMember(Name = "caster_team_slot")]
        public byte CasterTeamSlot;
        [DataMember(Name = "resolved_power")]
        public int ResolvedPower;
        [DataMember(Name = "allow_sub_squad_targeting")]
        public bool AllowSubSquadTargeting;
        [DataMember(Name = "distribution")]
        public DamageDistribution Distribution;

        public Projectile(
            ulong Id,
            ulong GameSessionId,
            ulong CasterEntityId,
            ulong AbilityId,
            DbVector3 Position,
            float DirectionX,
            float DirectionY,
            float DirectionZ,
            float Speed,
            float Radius,
            float MaxRange,
            float DistanceTraveled,
            byte CasterTeamSlot,
            int ResolvedPower,
            bool AllowSubSquadTargeting,
            DamageDistribution Distribution
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.CasterEntityId = CasterEntityId;
            this.AbilityId = AbilityId;
            this.Position = Position;
            this.DirectionX = DirectionX;
            this.DirectionY = DirectionY;
            this.DirectionZ = DirectionZ;
            this.Speed = Speed;
            this.Radius = Radius;
            this.MaxRange = MaxRange;
            this.DistanceTraveled = DistanceTraveled;
            this.CasterTeamSlot = CasterTeamSlot;
            this.ResolvedPower = ResolvedPower;
            this.AllowSubSquadTargeting = AllowSubSquadTargeting;
            this.Distribution = Distribution;
        }

        public Projectile()
        {
            this.Position = new();
        }
    }
}
