// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoadSegment
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "team_slot")]
        public byte TeamSlot;
        [DataMember(Name = "connected_to_entity_id")]
        public ulong ConnectedToEntityId;
        [DataMember(Name = "level")]
        public byte Level;

        public RoadSegment(
            ulong EntityId,
            ulong GameSessionId,
            byte TeamSlot,
            ulong ConnectedToEntityId,
            byte Level
        )
        {
            this.EntityId = EntityId;
            this.GameSessionId = GameSessionId;
            this.TeamSlot = TeamSlot;
            this.ConnectedToEntityId = ConnectedToEntityId;
            this.Level = Level;
        }

        public RoadSegment()
        {
        }
    }
}
