// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SkillDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "ability_ids")]
        public System.Collections.Generic.List<ulong> AbilityIds;
        [DataMember(Name = "archetype_def_id")]
        public ulong ArchetypeDefId;
        [DataMember(Name = "grants_mana")]
        public bool GrantsMana;

        public SkillDef(
            ulong Id,
            string Name,
            string Description,
            System.Collections.Generic.List<ulong> AbilityIds,
            ulong ArchetypeDefId,
            bool GrantsMana
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.AbilityIds = AbilityIds;
            this.ArchetypeDefId = ArchetypeDefId;
            this.GrantsMana = GrantsMana;
        }

        public SkillDef()
        {
            this.Name = "";
            this.Description = "";
            this.AbilityIds = new();
        }
    }
}
