// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Soldier
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "owner_player_id")]
        public ulong? OwnerPlayerId;
        [DataMember(Name = "health")]
        public int Health;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "armor")]
        public int Armor;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation_y")]
        public float RotationY;
        [DataMember(Name = "dead")]
        public bool Dead;
        [DataMember(Name = "died_at")]
        public SpacetimeDB.Timestamp? DiedAt;
        [DataMember(Name = "formation_index")]
        public byte FormationIndex;

        public Soldier(
            ulong Id,
            ulong GameSessionId,
            ulong? OwnerPlayerId,
            int Health,
            int MaxHealth,
            int Armor,
            DbVector3 Position,
            float RotationY,
            bool Dead,
            SpacetimeDB.Timestamp? DiedAt,
            byte FormationIndex
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.Armor = Armor;
            this.Position = Position;
            this.RotationY = RotationY;
            this.Dead = Dead;
            this.DiedAt = DiedAt;
            this.FormationIndex = FormationIndex;
        }

        public Soldier()
        {
            this.Position = new();
        }
    }
}
