// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Soldier
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_player_id")]
        public ulong? OwnerPlayerId;
        [DataMember(Name = "formation_index")]
        public byte FormationIndex;

        public Soldier(
            ulong EntityId,
            ulong? OwnerPlayerId,
            byte FormationIndex
        )
        {
            this.EntityId = EntityId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.FormationIndex = FormationIndex;
        }

        public Soldier()
        {
        }
    }
}
