// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Squad
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "parent_squad_id")]
        public ulong ParentSquadId;
        [DataMember(Name = "owner_player_id")]
        public ulong? OwnerPlayerId;
        [DataMember(Name = "cohesion_radius")]
        public float CohesionRadius;
        [DataMember(Name = "center_position")]
        public DbVector3 CenterPosition;
        [DataMember(Name = "entity_id")]
        public ulong EntityId;

        public Squad(
            ulong Id,
            ulong GameSessionId,
            ulong ParentSquadId,
            ulong? OwnerPlayerId,
            float CohesionRadius,
            DbVector3 CenterPosition,
            ulong EntityId
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.ParentSquadId = ParentSquadId;
            this.OwnerPlayerId = OwnerPlayerId;
            this.CohesionRadius = CohesionRadius;
            this.CenterPosition = CenterPosition;
            this.EntityId = EntityId;
        }

        public Squad()
        {
            this.CenterPosition = new();
        }
    }
}
