// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "primary_ability_id")]
        public ulong PrimaryAbilityId;
        [DataMember(Name = "grants_supplies")]
        public bool GrantsSupplies;

        public WeaponDef(
            ulong Id,
            string Name,
            string Description,
            ulong PrimaryAbilityId,
            bool GrantsSupplies
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.PrimaryAbilityId = PrimaryAbilityId;
            this.GrantsSupplies = GrantsSupplies;
        }

        public WeaponDef()
        {
            this.Name = "";
            this.Description = "";
        }
    }
}
