// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "primary_ability_id")]
        public ulong PrimaryAbilityId;
        [DataMember(Name = "grants_supplies")]
        public bool GrantsSupplies;
        [DataMember(Name = "mode")]
        public FireMode Mode;
        [DataMember(Name = "pellet_count")]
        public byte PelletCount;
        [DataMember(Name = "spread_angle_deg")]
        public float SpreadAngleDeg;
        [DataMember(Name = "clip_size")]
        public int ClipSize;
        [DataMember(Name = "reload_time_ms")]
        public ulong ReloadTimeMs;

        public WeaponDef(
            ulong Id,
            string Name,
            string Description,
            ulong PrimaryAbilityId,
            bool GrantsSupplies,
            FireMode Mode,
            byte PelletCount,
            float SpreadAngleDeg,
            int ClipSize,
            ulong ReloadTimeMs
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.PrimaryAbilityId = PrimaryAbilityId;
            this.GrantsSupplies = GrantsSupplies;
            this.Mode = Mode;
            this.PelletCount = PelletCount;
            this.SpreadAngleDeg = SpreadAngleDeg;
            this.ClipSize = ClipSize;
            this.ReloadTimeMs = ReloadTimeMs;
        }

        public WeaponDef()
        {
            this.Name = "";
            this.Description = "";
        }
    }
}
