# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsMessageTable extends _ModuleTable

var id: TvsMessageIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "message")
	id = TvsMessageIdUniqueIndex.new(p_local_db)

func iter() -> Array[TvsMessage]:
	var rows: Array = super()
	var typed_array: Array[TvsMessage] = []
	typed_array.assign(rows)
	return typed_array
