# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsGamePlayerTable extends _ModuleTable

var id: TvsGamePlayerIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "game_player")
	id = TvsGamePlayerIdUniqueIndex.new(p_local_db)

func iter() -> Array[TvsGamePlayer]:
	var rows: Array = super()
	var typed_array: Array[TvsGamePlayer] = []
	typed_array.assign(rows)
	return typed_array
