# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsPlayerIdentityUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[PackedByteArray, TvsPlayer] = {}

func _init(p_local_db: LocalDatabase) -> void:
	set_meta("table_name", "player")
	set_meta("field_name", "identity")
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: PackedByteArray) -> TvsPlayer:
	return _cache.get(col_val, null)
