# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsChatSessionPlayerTable extends _ModuleTable

var id: TvsChatSessionPlayerIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "chat_session_player")
	id = TvsChatSessionPlayerIdUniqueIndex.new(p_local_db)

func iter() -> Array[TvsChatSessionPlayer]:
	var rows: Array = super()
	var typed_array: Array[TvsChatSessionPlayer] = []
	typed_array.assign(rows)
	return typed_array
