# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name TvsGameSessionIdUniqueIndex extends _ModuleTableUniqueIndex

var _cache: Dictionary[int, TvsGameSession] = {}

func _init(p_local_db: LocalDatabase) -> void:
	set_meta("table_name", "game_session")
	set_meta("field_name", "id")
	_connect_cache_to_db(_cache, p_local_db)

func find(col_val: int) -> TvsGameSession:
	return _cache.get(col_val, null)
