// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "type")]
        public AbilityType Type;
        [DataMember(Name = "valid_targets")]
        public System.Collections.Generic.List<TargetType> ValidTargets;
        [DataMember(Name = "base_power")]
        public int BasePower;
        [DataMember(Name = "base_range")]
        public float BaseRange;
        [DataMember(Name = "base_radius")]
        public float BaseRadius;
        [DataMember(Name = "cooldown_ms")]
        public ulong CooldownMs;
        [DataMember(Name = "resource_costs")]
        public System.Collections.Generic.List<ResourceCost> ResourceCosts;
        [DataMember(Name = "granted_mods")]
        public System.Collections.Generic.List<AbilityMod> GrantedMods;
        [DataMember(Name = "effect_duration_ms")]
        public ulong EffectDurationMs;
        [DataMember(Name = "affected_ability_ids")]
        public System.Collections.Generic.List<ulong> AffectedAbilityIds;

        public AbilityDef(
            ulong Id,
            string Name,
            string Description,
            AbilityType Type,
            System.Collections.Generic.List<TargetType> ValidTargets,
            int BasePower,
            float BaseRange,
            float BaseRadius,
            ulong CooldownMs,
            System.Collections.Generic.List<ResourceCost> ResourceCosts,
            System.Collections.Generic.List<AbilityMod> GrantedMods,
            ulong EffectDurationMs,
            System.Collections.Generic.List<ulong> AffectedAbilityIds
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Type = Type;
            this.ValidTargets = ValidTargets;
            this.BasePower = BasePower;
            this.BaseRange = BaseRange;
            this.BaseRadius = BaseRadius;
            this.CooldownMs = CooldownMs;
            this.ResourceCosts = ResourceCosts;
            this.GrantedMods = GrantedMods;
            this.EffectDurationMs = EffectDurationMs;
            this.AffectedAbilityIds = AffectedAbilityIds;
        }

        public AbilityDef()
        {
            this.Name = "";
            this.Description = "";
            this.ValidTargets = new();
            this.ResourceCosts = new();
            this.GrantedMods = new();
            this.AffectedAbilityIds = new();
        }
    }
}
