// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PositionOverride
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "position")]
        public DbVector3 Position;

        public PositionOverride(
            ulong Id,
            ulong PlayerId,
            ulong GameSessionId,
            DbVector3 Position
        )
        {
            this.Id = Id;
            this.PlayerId = PlayerId;
            this.GameSessionId = GameSessionId;
            this.Position = Position;
        }

        public PositionOverride()
        {
            this.Position = new();
        }
    }
}
