// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResourcePool
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_player_id")]
        public ulong GamePlayerId;
        [DataMember(Name = "kind")]
        public ResourceKind Kind;
        [DataMember(Name = "current")]
        public int Current;
        [DataMember(Name = "max")]
        public int Max;

        public ResourcePool(
            ulong Id,
            ulong GamePlayerId,
            ResourceKind Kind,
            int Current,
            int Max
        )
        {
            this.Id = Id;
            this.GamePlayerId = GamePlayerId;
            this.Kind = Kind;
            this.Current = Current;
            this.Max = Max;
        }

        public ResourcePool()
        {
        }
    }
}
