// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResourceCost
    {
        [DataMember(Name = "kind")]
        public ResourceKind Kind;
        [DataMember(Name = "amount")]
        public int Amount;

        public ResourceCost(
            ResourceKind Kind,
            int Amount
        )
        {
            this.Kind = Kind;
            this.Amount = Amount;
        }

        public ResourceCost()
        {
        }
    }
}
