// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TerrainFeature
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "game_session_id")]
        public ulong GameSessionId;
        [DataMember(Name = "type")]
        public TerrainType Type;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "size_x")]
        public float SizeX;
        [DataMember(Name = "size_y")]
        public float SizeY;
        [DataMember(Name = "size_z")]
        public float SizeZ;
        [DataMember(Name = "rotation_y")]
        public float RotationY;
        [DataMember(Name = "team_index")]
        public byte TeamIndex;

        public TerrainFeature(
            ulong Id,
            ulong GameSessionId,
            TerrainType Type,
            float PosX,
            float PosY,
            float PosZ,
            float SizeX,
            float SizeY,
            float SizeZ,
            float RotationY,
            byte TeamIndex
        )
        {
            this.Id = Id;
            this.GameSessionId = GameSessionId;
            this.Type = Type;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.SizeX = SizeX;
            this.SizeY = SizeY;
            this.SizeZ = SizeZ;
            this.RotationY = RotationY;
            this.TeamIndex = TeamIndex;
        }

        public TerrainFeature()
        {
        }
    }
}
