// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponDef
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "primary_ability_id")]
        public ulong PrimaryAbilityId;
        [DataMember(Name = "secondary_ability_id")]
        public ulong SecondaryAbilityId;
        [DataMember(Name = "bonus_ability_ids")]
        public System.Collections.Generic.List<ulong> BonusAbilityIds;
        [DataMember(Name = "primary_mods")]
        public System.Collections.Generic.List<AbilityMod> PrimaryMods;
        [DataMember(Name = "secondary_mods")]
        public System.Collections.Generic.List<AbilityMod> SecondaryMods;

        public WeaponDef(
            ulong Id,
            string Name,
            string Description,
            ulong PrimaryAbilityId,
            ulong SecondaryAbilityId,
            System.Collections.Generic.List<ulong> BonusAbilityIds,
            System.Collections.Generic.List<AbilityMod> PrimaryMods,
            System.Collections.Generic.List<AbilityMod> SecondaryMods
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.PrimaryAbilityId = PrimaryAbilityId;
            this.SecondaryAbilityId = SecondaryAbilityId;
            this.BonusAbilityIds = BonusAbilityIds;
            this.PrimaryMods = PrimaryMods;
            this.SecondaryMods = SecondaryMods;
        }

        public WeaponDef()
        {
            this.Name = "";
            this.Description = "";
            this.BonusAbilityIds = new();
            this.PrimaryMods = new();
            this.SecondaryMods = new();
        }
    }
}
