// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CastSpellHandler(ReducerEventContext ctx, ulong gameId, SpacetimeDB.Types.SpellId spellId, ulong? targetGamePlayerId);
        public event CastSpellHandler? OnCastSpell;

        public void CastSpell(ulong gameId, SpacetimeDB.Types.SpellId spellId, ulong? targetGamePlayerId)
        {
            conn.InternalCallReducer(new Reducer.CastSpell(gameId, spellId, targetGamePlayerId));
        }

        public bool InvokeCastSpell(ReducerEventContext ctx, Reducer.CastSpell args)
        {
            if (OnCastSpell == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCastSpell(
                ctx,
                args.GameId,
                args.SpellId,
                args.TargetGamePlayerId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CastSpell : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "spell_id")]
            public SpellId SpellId;
            [DataMember(Name = "target_game_player_id")]
            public ulong? TargetGamePlayerId;

            public CastSpell(
                ulong GameId,
                SpellId SpellId,
                ulong? TargetGamePlayerId
            )
            {
                this.GameId = GameId;
                this.SpellId = SpellId;
                this.TargetGamePlayerId = TargetGamePlayerId;
            }

            public CastSpell()
            {
            }

            string IReducerArgs.ReducerName => "cast_spell";
        }
    }
}
