// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateGameHandler(ReducerEventContext ctx, uint maxPlayers, uint? respawnTimerSeconds);
        public event CreateGameHandler? OnCreateGame;

        public void CreateGame(uint maxPlayers, uint? respawnTimerSeconds)
        {
            conn.InternalCallReducer(new Reducer.CreateGame(maxPlayers, respawnTimerSeconds));
        }

        public bool InvokeCreateGame(ReducerEventContext ctx, Reducer.CreateGame args)
        {
            if (OnCreateGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateGame(
                ctx,
                args.MaxPlayers,
                args.RespawnTimerSeconds
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "max_players")]
            public uint MaxPlayers;
            [DataMember(Name = "respawn_timer_seconds")]
            public uint? RespawnTimerSeconds;

            public CreateGame(
                uint MaxPlayers,
                uint? RespawnTimerSeconds
            )
            {
                this.MaxPlayers = MaxPlayers;
                this.RespawnTimerSeconds = RespawnTimerSeconds;
            }

            public CreateGame()
            {
            }

            string IReducerArgs.ReducerName => "create_game";
        }
    }
}
