// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateGameAndJoinHandler(ReducerEventContext ctx, uint maxPlayers);
        public event CreateGameAndJoinHandler? OnCreateGameAndJoin;

        public void CreateGameAndJoin(uint maxPlayers)
        {
            conn.InternalCallReducer(new Reducer.CreateGameAndJoin(maxPlayers));
        }

        public bool InvokeCreateGameAndJoin(ReducerEventContext ctx, Reducer.CreateGameAndJoin args)
        {
            if (OnCreateGameAndJoin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateGameAndJoin(
                ctx,
                args.MaxPlayers
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateGameAndJoin : Reducer, IReducerArgs
        {
            [DataMember(Name = "max_players")]
            public uint MaxPlayers;

            public CreateGameAndJoin(uint MaxPlayers)
            {
                this.MaxPlayers = MaxPlayers;
            }

            public CreateGameAndJoin()
            {
            }

            string IReducerArgs.ReducerName => "create_game_and_join";
        }
    }
}
