// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteGameHandler(ReducerEventContext ctx, ulong gameId);
        public event DeleteGameHandler? OnDeleteGame;

        public void DeleteGame(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.DeleteGame(gameId));
        }

        public bool InvokeDeleteGame(ReducerEventContext ctx, Reducer.DeleteGame args)
        {
            if (OnDeleteGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteGame(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public DeleteGame(ulong GameId)
            {
                this.GameId = GameId;
            }

            public DeleteGame()
            {
            }

            string IReducerArgs.ReducerName => "delete_game";
        }
    }
}
