// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void KickPlayerFromGameHandler(ReducerEventContext ctx, ulong gameId, string playerName);
        public event KickPlayerFromGameHandler? OnKickPlayerFromGame;

        public void KickPlayerFromGame(ulong gameId, string playerName)
        {
            conn.InternalCallReducer(new Reducer.KickPlayerFromGame(gameId, playerName));
        }

        public bool InvokeKickPlayerFromGame(ReducerEventContext ctx, Reducer.KickPlayerFromGame args)
        {
            if (OnKickPlayerFromGame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnKickPlayerFromGame(
                ctx,
                args.GameId,
                args.PlayerName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class KickPlayerFromGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "player_name")]
            public string PlayerName;

            public KickPlayerFromGame(
                ulong GameId,
                string PlayerName
            )
            {
                this.GameId = GameId;
                this.PlayerName = PlayerName;
            }

            public KickPlayerFromGame()
            {
                this.PlayerName = "";
            }

            string IReducerArgs.ReducerName => "kick_player_from_game";
        }
    }
}
