// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MovePlayerHandler(ReducerEventContext ctx, ulong gameId, SpacetimeDB.Types.DbVector3 newPosition);
        public event MovePlayerHandler? OnMovePlayer;

        public void MovePlayer(ulong gameId, SpacetimeDB.Types.DbVector3 newPosition)
        {
            conn.InternalCallReducer(new Reducer.MovePlayer(gameId, newPosition));
        }

        public bool InvokeMovePlayer(ReducerEventContext ctx, Reducer.MovePlayer args)
        {
            if (OnMovePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMovePlayer(
                ctx,
                args.GameId,
                args.NewPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MovePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "new_position")]
            public DbVector3 NewPosition;

            public MovePlayer(
                ulong GameId,
                DbVector3 NewPosition
            )
            {
                this.GameId = GameId;
                this.NewPosition = NewPosition;
            }

            public MovePlayer()
            {
                this.NewPosition = new();
            }

            string IReducerArgs.ReducerName => "move_player";
        }
    }
}
