// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportProjectileHitHandler(ReducerEventContext ctx, ulong gameId, ulong projectileId, ulong hitEntityId, SpacetimeDB.Types.DbVector3 hitPosition);
        public event ReportProjectileHitHandler? OnReportProjectileHit;

        public void ReportProjectileHit(ulong gameId, ulong projectileId, ulong hitEntityId, SpacetimeDB.Types.DbVector3 hitPosition)
        {
            conn.InternalCallReducer(new Reducer.ReportProjectileHit(gameId, projectileId, hitEntityId, hitPosition));
        }

        public bool InvokeReportProjectileHit(ReducerEventContext ctx, Reducer.ReportProjectileHit args)
        {
            if (OnReportProjectileHit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportProjectileHit(
                ctx,
                args.GameId,
                args.ProjectileId,
                args.HitEntityId,
                args.HitPosition
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportProjectileHit : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "projectile_id")]
            public ulong ProjectileId;
            [DataMember(Name = "hit_entity_id")]
            public ulong HitEntityId;
            [DataMember(Name = "hit_position")]
            public DbVector3 HitPosition;

            public ReportProjectileHit(
                ulong GameId,
                ulong ProjectileId,
                ulong HitEntityId,
                DbVector3 HitPosition
            )
            {
                this.GameId = GameId;
                this.ProjectileId = ProjectileId;
                this.HitEntityId = HitEntityId;
                this.HitPosition = HitPosition;
            }

            public ReportProjectileHit()
            {
                this.HitPosition = new();
            }

            string IReducerArgs.ReducerName => "report_projectile_hit";
        }
    }
}
