// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetLoadoutHandler(ReducerEventContext ctx, ulong gameId, ulong weaponDefId, ulong skillDefId);
        public event SetLoadoutHandler? OnSetLoadout;

        public void SetLoadout(ulong gameId, ulong weaponDefId, ulong skillDefId)
        {
            conn.InternalCallReducer(new Reducer.SetLoadout(gameId, weaponDefId, skillDefId));
        }

        public bool InvokeSetLoadout(ReducerEventContext ctx, Reducer.SetLoadout args)
        {
            if (OnSetLoadout == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetLoadout(
                ctx,
                args.GameId,
                args.WeaponDefId,
                args.SkillDefId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetLoadout : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "weapon_def_id")]
            public ulong WeaponDefId;
            [DataMember(Name = "skill_def_id")]
            public ulong SkillDefId;

            public SetLoadout(
                ulong GameId,
                ulong WeaponDefId,
                ulong SkillDefId
            )
            {
                this.GameId = GameId;
                this.WeaponDefId = WeaponDefId;
                this.SkillDefId = SkillDefId;
            }

            public SetLoadout()
            {
            }

            string IReducerArgs.ReducerName => "set_loadout";
        }
    }
}
