// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StopResupplyHandler(ReducerEventContext ctx, ulong gameId);
        public event StopResupplyHandler? OnStopResupply;

        public void StopResupply(ulong gameId)
        {
            conn.InternalCallReducer(new Reducer.StopResupply(gameId));
        }

        public bool InvokeStopResupply(ReducerEventContext ctx, Reducer.StopResupply args)
        {
            if (OnStopResupply == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStopResupply(
                ctx,
                args.GameId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StopResupply : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;

            public StopResupply(ulong GameId)
            {
                this.GameId = GameId;
            }

            public StopResupply()
            {
            }

            string IReducerArgs.ReducerName => "stop_resupply";
        }
    }
}
