// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UseAbilityHandler(ReducerEventContext ctx, ulong gameId, ulong abilityId, ulong? targetEntityId, SpacetimeDB.Types.DbVector3? targetPosition, float? targetRotationY);
        public event UseAbilityHandler? OnUseAbility;

        public void UseAbility(ulong gameId, ulong abilityId, ulong? targetEntityId, SpacetimeDB.Types.DbVector3? targetPosition, float? targetRotationY)
        {
            conn.InternalCallReducer(new Reducer.UseAbility(gameId, abilityId, targetEntityId, targetPosition, targetRotationY));
        }

        public bool InvokeUseAbility(ReducerEventContext ctx, Reducer.UseAbility args)
        {
            if (OnUseAbility == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUseAbility(
                ctx,
                args.GameId,
                args.AbilityId,
                args.TargetEntityId,
                args.TargetPosition,
                args.TargetRotationY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UseAbility : Reducer, IReducerArgs
        {
            [DataMember(Name = "game_id")]
            public ulong GameId;
            [DataMember(Name = "ability_id")]
            public ulong AbilityId;
            [DataMember(Name = "target_entity_id")]
            public ulong? TargetEntityId;
            [DataMember(Name = "target_position")]
            public DbVector3? TargetPosition;
            [DataMember(Name = "target_rotation_y")]
            public float? TargetRotationY;

            public UseAbility(
                ulong GameId,
                ulong AbilityId,
                ulong? TargetEntityId,
                DbVector3? TargetPosition,
                float? TargetRotationY
            )
            {
                this.GameId = GameId;
                this.AbilityId = AbilityId;
                this.TargetEntityId = TargetEntityId;
                this.TargetPosition = TargetPosition;
                this.TargetRotationY = TargetRotationY;
            }

            public UseAbility()
            {
            }

            string IReducerArgs.ReducerName => "use_ability";
        }
    }
}
