// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveEffectHandle : RemoteTableHandle<EventContext, ActiveEffect>
        {
            protected override string RemoteTableName => "active_effect";

            public sealed class GamePlayerIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveEffect row) => row.GamePlayerId;

                public GamePlayerIdIndex(ActiveEffectHandle table) : base(table) { }
            }

            public readonly GamePlayerIdIndex GamePlayerId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveEffect row) => row.Id;

                public IdUniqueIndex(ActiveEffectHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ActiveEffectHandle(DbConnection conn) : base(conn)
            {
                GamePlayerId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ActiveEffect row) => row.Id;
        }

        public readonly ActiveEffectHandle ActiveEffect;
    }

    public sealed class ActiveEffectCols
    {
        public global::SpacetimeDB.Col<ActiveEffect, ulong> Id { get; }
        public global::SpacetimeDB.Col<ActiveEffect, ulong> GamePlayerId { get; }
        public global::SpacetimeDB.Col<ActiveEffect, ulong> CasterGamePlayerId { get; }
        public global::SpacetimeDB.Col<ActiveEffect, ulong> SourceAbilityId { get; }
        public global::SpacetimeDB.Col<ActiveEffect, System.Collections.Generic.List<AbilityMod>> Mods { get; }
        public global::SpacetimeDB.Col<ActiveEffect, System.Collections.Generic.List<ulong>> AffectedAbilityIds { get; }
        public global::SpacetimeDB.Col<ActiveEffect, SpacetimeDB.Timestamp> ExpiresAt { get; }

        public ActiveEffectCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ActiveEffect, ulong>(tableName, "id");
            GamePlayerId = new global::SpacetimeDB.Col<ActiveEffect, ulong>(tableName, "game_player_id");
            CasterGamePlayerId = new global::SpacetimeDB.Col<ActiveEffect, ulong>(tableName, "caster_game_player_id");
            SourceAbilityId = new global::SpacetimeDB.Col<ActiveEffect, ulong>(tableName, "source_ability_id");
            Mods = new global::SpacetimeDB.Col<ActiveEffect, System.Collections.Generic.List<AbilityMod>>(tableName, "mods");
            AffectedAbilityIds = new global::SpacetimeDB.Col<ActiveEffect, System.Collections.Generic.List<ulong>>(tableName, "affected_ability_ids");
            ExpiresAt = new global::SpacetimeDB.Col<ActiveEffect, SpacetimeDB.Timestamp>(tableName, "expires_at");
        }
    }

    public sealed class ActiveEffectIxCols
    {
        public global::SpacetimeDB.IxCol<ActiveEffect, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ActiveEffect, ulong> GamePlayerId { get; }

        public ActiveEffectIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ActiveEffect, ulong>(tableName, "id");
            GamePlayerId = new global::SpacetimeDB.IxCol<ActiveEffect, ulong>(tableName, "game_player_id");
        }
    }
}
