# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsGamePlayer extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['game_player']

@export var id: int
@export var game_session_id: int
@export var player_identity: PackedByteArray
@export var team_slot: int
@export var position: TvsDbVector3

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_game_session_id', &'u64')
	set_meta('bsatn_type_player_identity', &'identity')
	set_meta('bsatn_type_team_slot', &'u8')
	set_meta('bsatn_type_position', &'TvsDbVector3')

## 0. id: int[br]
## 1. game_session_id: int[br]
## 2. player_identity: PackedByteArray[br]
## 3. team_slot: int[br]
## 4. position: TvsDbVector3[br]
static func create(p_id: int, p_game_session_id: int, p_player_identity: PackedByteArray, p_team_slot: int, p_position: TvsDbVector3) -> TvsGamePlayer:
	var result: TvsGamePlayer = TvsGamePlayer.new()
	result.id = p_id
	result.game_session_id = p_game_session_id
	result.player_identity = p_player_identity
	result.team_slot = p_team_slot
	result.position = p_position
	return result
