# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsChatSession extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['chat_session']

@export var id: int
@export var time_created: int
@export var owner: PackedByteArray
@export var name: String
@export var active: bool

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_time_created', &'i64')
	set_meta('bsatn_type_owner', &'identity')
	set_meta('bsatn_type_name', &'string')
	set_meta('bsatn_type_active', &'bool')

## 0. id: int[br]
## 1. time_created: int[br]
## 2. owner: PackedByteArray[br]
## 3. name: String[br]
## 4. active: bool[br]
static func create(p_id: int, p_time_created: int, p_owner: PackedByteArray, p_name: String, p_active: bool) -> TvsChatSession:
	var result: TvsChatSession = TvsChatSession.new()
	result.id = p_id
	result.time_created = p_time_created
	result.owner = p_owner
	result.name = p_name
	result.active = p_active
	return result
