# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsChatSessionPlayer extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['chat_session_player']

@export var id: int
@export var player_identity: PackedByteArray
@export var session_id: int

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_player_identity', &'identity')
	set_meta('bsatn_type_session_id', &'u64')

## 0. id: int[br]
## 1. player_identity: PackedByteArray[br]
## 2. session_id: int[br]
static func create(p_id: int, p_player_identity: PackedByteArray, p_session_id: int) -> TvsChatSessionPlayer:
	var result: TvsChatSessionPlayer = TvsChatSessionPlayer.new()
	result.id = p_id
	result.player_identity = p_player_identity
	result.session_id = p_session_id
	return result
