# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsGameSession extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['game_session']

@export var id: int
@export var owner_identity: PackedByteArray
@export var state: TvsModuleClient.Types.SessionState
@export var max_players: int
@export var created_at: int

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_owner_identity', &'identity')
	set_meta('bsatn_type_state', &'u8')
	set_meta('bsatn_type_max_players', &'u32')
	set_meta('bsatn_type_created_at', &'i64')

## 0. id: int[br]
## 1. owner_identity: PackedByteArray[br]
## 2. state: TvsModuleClient.Types.SessionState[br]
## 3. max_players: int[br]
## 4. created_at: int[br]
static func create(p_id: int, p_owner_identity: PackedByteArray, p_state: TvsModuleClient.Types.SessionState, p_max_players: int, p_created_at: int) -> TvsGameSession:
	var result: TvsGameSession = TvsGameSession.new()
	result.id = p_id
	result.owner_identity = p_owner_identity
	result.state = p_state
	result.max_players = p_max_players
	result.created_at = p_created_at
	return result
