# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsMessage extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['message']

@export var id: int
@export var body: String
@export var session_id: int
@export var sender: PackedByteArray
@export var deleted: bool
@export var time_sent: int

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'id')
	set_meta('bsatn_type_id', &'u64')
	set_meta('bsatn_type_body', &'string')
	set_meta('bsatn_type_session_id', &'u64')
	set_meta('bsatn_type_sender', &'identity')
	set_meta('bsatn_type_deleted', &'bool')
	set_meta('bsatn_type_time_sent', &'i64')

## 0. id: int[br]
## 1. body: String[br]
## 2. session_id: int[br]
## 3. sender: PackedByteArray[br]
## 4. deleted: bool[br]
## 5. time_sent: int[br]
static func create(p_id: int, p_body: String, p_session_id: int, p_sender: PackedByteArray, p_deleted: bool, p_time_sent: int) -> TvsMessage:
	var result: TvsMessage = TvsMessage.new()
	result.id = p_id
	result.body = p_body
	result.session_id = p_session_id
	result.sender = p_sender
	result.deleted = p_deleted
	result.time_sent = p_time_sent
	return result
