# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsDbVector3 extends Resource

const module_name : String = "Tvs"
const table_names: Array[String] = []

@export var x: float
@export var y: float
@export var z: float

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('bsatn_type_x', &'f32')
	set_meta('bsatn_type_y', &'f32')
	set_meta('bsatn_type_z', &'f32')

## 0. x: float[br]
## 1. y: float[br]
## 2. z: float[br]
static func create(p_x: float, p_y: float, p_z: float) -> TvsDbVector3:
	var result: TvsDbVector3 = TvsDbVector3.new()
	result.x = p_x
	result.y = p_y
	result.z = p_z
	return result
