# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name TvsPlayer extends _ModuleTableType

const module_name : String = "Tvs"
const table_names: Array[String] = ['player']

@export var identity: PackedByteArray
@export var name: String
@export var online: bool

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('primary_key', 'identity')
	set_meta('bsatn_type_identity', &'identity')
	set_meta('bsatn_type_name', &'string')
	set_meta('bsatn_type_online', &'bool')

## 0. identity: PackedByteArray[br]
## 1. name: String[br]
## 2. online: bool[br]
static func create(p_identity: PackedByteArray, p_name: String, p_online: bool) -> TvsPlayer:
	var result: TvsPlayer = TvsPlayer.new()
	result.identity = p_identity
	result.name = p_name
	result.online = p_online
	return result
